import crypto from 'node:crypto';
import { db } from '@/lib/db';
const TABLE='custom_api_connections';const DELIVERY='custom_webhook_deliveries';const LOG='custom_api_request_logs';let ready=false;
export type CustomConnection={id:string;name:string;baseUrl:string|null;apiKeyHash:string;apiKeyEnc:string|null;apiKeyLast4:string;productsEndpoint:string;ordersEndpoint:string;customersEndpoint:string;orderUpdateEndpoint:string;webhookUrl:string|null;webhookSecretEnc:string|null;webhookToken:string;scopes:string;enabled:number|boolean};
export async function ensureCustomApiTables(){if(ready)return;await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS ${TABLE} (id VARCHAR(64) PRIMARY KEY,name VARCHAR(191) NOT NULL,base_url TEXT NULL,api_key_hash VARCHAR(64) NOT NULL UNIQUE,api_key_enc TEXT NULL,api_key_last4 VARCHAR(8) NOT NULL,products_endpoint VARCHAR(255) NOT NULL DEFAULT '/api/v1/products',orders_endpoint VARCHAR(255) NOT NULL DEFAULT '/api/v1/orders',customers_endpoint VARCHAR(255) NOT NULL DEFAULT '/api/v1/customers',order_update_endpoint VARCHAR(255) NOT NULL DEFAULT '/api/v1/orders/{id}',webhook_url TEXT NULL,webhook_secret_enc TEXT NULL,webhook_token VARCHAR(128) NOT NULL UNIQUE,scopes TEXT NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`);await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS ${DELIVERY} (id VARCHAR(64) PRIMARY KEY,connection_id VARCHAR(64) NOT NULL,event_id VARCHAR(128) NOT NULL UNIQUE,event_type VARCHAR(100) NOT NULL,url TEXT NOT NULL,payload JSON NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'PENDING',attempts INT NOT NULL DEFAULT 0,last_error TEXT NULL,next_attempt_at TIMESTAMP NULL,delivered_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`);await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS ${LOG} (id VARCHAR(64) PRIMARY KEY,connection_id VARCHAR(64) NULL,method VARCHAR(10) NOT NULL,path VARCHAR(255) NOT NULL,status INT NOT NULL,ip VARCHAR(64) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`);ready=true;}
const key=()=>crypto.createHash('sha256').update(process.env.SESSION_SECRET||'').digest();
export function encryptSecret(value:string){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',key(),iv);const enc=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${enc.toString('base64url')}`;}
export function decryptSecret(value:string){const [i,t,e]=value.split('.');const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(i,'base64url'));d.setAuthTag(Buffer.from(t,'base64url'));return Buffer.concat([d.update(Buffer.from(e,'base64url')),d.final()]).toString('utf8');}
export const sha256=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');export const randomSecret=(prefix:string)=>`${prefix}${crypto.randomBytes(32).toString('base64url')}`;export function signature(secret:string,timestamp:string,body:string){return `sha256=${crypto.createHmac('sha256',secret).update(`${timestamp}.${body}`).digest('hex')}`;}export function safeEqual(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&crypto.timingSafeEqual(x,y);}
export async function getConnectionByApiKey(apiKey:string){await ensureCustomApiTables();const rows=await db.$queryRawUnsafe<CustomConnection[]>(`SELECT * FROM ${TABLE} WHERE api_key_hash=? AND enabled=true LIMIT 1`,sha256(apiKey));return rows[0]||null;}
export async function getConnectionByToken(token:string){await ensureCustomApiTables();const rows=await db.$queryRawUnsafe<CustomConnection[]>(`SELECT * FROM ${TABLE} WHERE webhook_token=? AND enabled=true LIMIT 1`,token);return rows[0]||null;}
export async function logCustomRequest(c:CustomConnection|null,req:Request,status:number){try{await ensureCustomApiTables();await db.$executeRawUnsafe(`INSERT INTO ${LOG}(id,connection_id,method,path,status,ip) VALUES(?,?,?,?,?,?)`,crypto.randomUUID(),c?.id||null,req.method,new URL(req.url).pathname,status,req.headers.get('x-forwarded-for')||null);}catch{}}
export async function queueWebhook(connection:CustomConnection,eventType:string,payload:unknown){if(!connection.webhookUrl)return;await ensureCustomApiTables();const body={event:eventType,id:`evt_${crypto.randomBytes(16).toString('hex')}`,timestamp:new Date().toISOString(),data:payload};await db.$executeRawUnsafe(`INSERT INTO ${DELIVERY}(id,connection_id,event_id,event_type,url,payload) VALUES(?,?,?,?,?,?)`,crypto.randomUUID(),connection.id,body.id,eventType,connection.webhookUrl,JSON.stringify(body));}
export async function queueConnectionEvent(eventType:string,payload:unknown){await ensureCustomApiTables();const rows=await db.$queryRawUnsafe<CustomConnection[]>(`SELECT * FROM ${TABLE} WHERE enabled=true AND webhook_url IS NOT NULL`);for(const c of rows)await queueWebhook(c,eventType,payload);}
export const normalizedStatuses=['pending','confirmed','processing','packed','shipped','out_for_delivery','delivered','cancelled','failed','refunded','returned'] as const;
export function toNormalizedStatus(status:string){const m:Record<string,string>={CREATED:'pending',PAYMENT_PENDING:'pending',CONFIRMED:'confirmed',PROCESSING:'processing',SHIPPED:'shipped',DELIVERED:'delivered',CANCELLED:'cancelled',RETURN_REQUESTED:'returned',RETURNED:'returned',REFUNDED:'refunded'};return m[status]||status.toLowerCase();}
