import type { Product } from '@/lib/catalog';
import { priyasaApi } from '@/lib/priyasa-api';

type ApiResponse = { success?: boolean; data?: any; message?: string };
export type StorefrontCategory = { id: string; name: string; slug: string; imageUrl: string; description?: string; products: any[]; _count?: { products?: number } };
export type HomeCmsSection = { id: string; type?: string; title?: string; subtitle?: string; imageUrl?: string; ctaHref?: string; ctaLabel?: string; sortOrder?: number; [key: string]: any };

async function coreFetch(path: string, init: RequestInit = {}): Promise<ApiResponse> {
  const { response, body } = await priyasaApi(path, init);
  if (!response.ok) throw new Error((body as any)?.message || `PriyasaCore request failed (${response.status})`);
  return (body || {}) as ApiResponse;
}
function listFrom(response: ApiResponse): any[] { const value = response.data; if (Array.isArray(value)) return value; if (Array.isArray(value?.data)) return value.data; return []; }
function mediaUrls(product: any): string[] { const media = product?.media; if (Array.isArray(media)) return media.map((item) => typeof item === 'string' ? item : item?.url || item?.image_url).filter(Boolean); if (media && typeof media === 'object') return Object.values(media).flatMap((item: any) => typeof item === 'string' ? [item] : [item?.url, item?.image_url]).filter(Boolean) as string[]; return []; }
function available(variant: any): number { const inventory = variant?.inventory; if (inventory) return Math.max(0, Number(inventory.quantity || 0) - Number(inventory.reserved_quantity || 0)); return Math.max(0, Number(variant?.stock || 0) - Number(variant?.reserved || 0)); }
function mapProduct(product: any): Product { const variants = Array.isArray(product?.variants) ? product.variants.filter((v: any) => v?.is_active !== false) : []; const inStock = variants.find((v: any) => available(v) > 0) || variants[0]; const urls = [...mediaUrls(product), ...variants.map((v: any) => v?.image_url).filter(Boolean)].filter((value, index, all) => all.indexOf(value) === index); const price = Number(inStock?.price ?? product?.price ?? 0); const mrp = Number(inStock?.mrp ?? product?.mrp ?? price); const category = product?.category; return { id: String(product.id), name: String(product.name || ''), slug: String(product.slug || product.id), category: String(category?.name || 'Priyasa'), categorySlug: category?.slug ? String(category.slug) : undefined, price, mrp, image: urls[0] || '/images/product-placeholder.svg', images: urls.length ? urls : ['/images/product-placeholder.svg'], colors: [...new Set(variants.map((v: any) => v?.color).filter(Boolean))] as string[], sizes: [...new Set(variants.map((v: any) => v?.size).filter(Boolean))] as string[], description: String(product?.short_description || product?.description || ''), variantId: inStock?.id ? String(inStock.id) : '', badge: mrp > price && price > 0 ? `${Math.round(((mrp - price) / mrp) * 100)}% OFF` : undefined }; }

export type ProductQuery = { categorySlug?: string; collectionSlug?: string; brand?: string; minPrice?: number; maxPrice?: number; inStock?: boolean; sort?: 'newest'|'price_asc'|'price_desc'|'name_asc'|'rating'; limit?: number; page?: number; search?: string };
export async function getStorefrontProducts(options: ProductQuery = {}): Promise<Product[]> { const params = new URLSearchParams(); if (options.categorySlug) params.set('category', options.categorySlug); if (options.collectionSlug) params.set('collection', options.collectionSlug); if (options.brand) params.set('brand', options.brand); if (options.minPrice !== undefined) params.set('min_price', String(options.minPrice)); if (options.maxPrice !== undefined) params.set('max_price', String(options.maxPrice)); if (options.inStock) params.set('in_stock', '1'); if (options.sort) params.set('sort', options.sort); if (options.search) params.set('search', options.search); params.set('per_page', String(Math.min(Math.max(options.limit || 24, 1), 100))); if (options.page) params.set('page', String(Math.max(1, options.page))); return listFrom(await coreFetch(`/api/v1/storefront/products?${params.toString()}`)).map(mapProduct); }
export async function getLatestLaunches(limit = 8) { return getStorefrontProducts({ limit, sort: 'newest' }); }
export async function getSearchProducts(query: string, limit = 24) { return getStorefrontProducts({ search: query, limit, sort: 'newest' }); }
export async function getBestSellers(limit = 8) { return getStorefrontProducts({ limit, sort: 'rating' }); }
export async function getSaleProducts(limit = 8) { return (await getStorefrontProducts({ limit: Math.min(100, limit * 3), sort: 'price_asc' })).filter((p) => p.price > 0 && p.mrp > p.price).slice(0, limit); }
export async function getProductsForHomeSection(type: string, limit = 8): Promise<Product[]> { const t = type.toLowerCase().trim(); if (t === 'products-sale' || t === 'sale') return getSaleProducts(limit); if (t === 'products-latest' || t === 'latest' || t === 'latest-collection') return getLatestLaunches(limit); if (t === 'products-best' || t === 'best-sellers' || t === 'trending') return getBestSellers(limit); if (t.startsWith('products-category:')) return getStorefrontProducts({ categorySlug: t.slice('products-category:'.length).trim(), limit }); return []; }
export async function getStorefrontProduct(slug: string) { const response = await coreFetch(`/api/v1/storefront/products/${encodeURIComponent(slug)}`); const payload = response.data; const product = payload?.product || payload; if (!product) return null; const mapped = mapProduct(product); const variants = Array.isArray(product.variants) ? product.variants.filter((v: any) => v?.is_active !== false) : []; return { ...mapped, variants: variants.map((variant: any) => ({ id: String(variant.id), color: variant.color, size: variant.size, price: Number(variant.price ?? product.price ?? 0), mrp: Number(variant.mrp ?? product.mrp ?? 0), stock: available(variant), sku: variant.sku })), rating: Number(product.approved_rating ?? 0), reviewCount: Number(product.approved_reviews_count ?? 0), relatedProducts: Array.isArray(payload?.related_products) ? payload.related_products.map(mapProduct) : [], fabric: product?.attributes?.fabric, care: product?.attributes?.care, seo: { title: product?.seo_title || product?.meta_title, description: product?.seo_description || product?.meta_description } }; }
export async function getStorefrontCategories(): Promise<StorefrontCategory[]> { return listFrom(await coreFetch('/api/v1/storefront/categories')).map((category: any) => ({ id: String(category.id), name: String(category.name || ''), slug: String(category.slug || category.id), imageUrl: category.image_url || category.imageUrl || category.media?.url || '', description: category.description ? String(category.description) : undefined, products: [], _count: category._count })); }
export async function getStorefrontCollections(withProducts = false) { return listFrom(await coreFetch(`/api/v1/storefront/collections${withProducts ? '?with_products=1' : ''}`)); }
export async function getStorefrontCollection(slug: string, page = 1, limit = 24) { const response = await coreFetch(`/api/v1/storefront/collections/${encodeURIComponent(slug)}?page=${page}&per_page=${limit}`); return response.data || null; }
export async function getActiveCms(key: string) { return (await coreFetch(`/api/v1/storefront/cms/${encodeURIComponent(key)}`).catch(() => ({ data: null }))).data || null; }
export async function getHomeCms(): Promise<HomeCmsSection[]> { const data = await getActiveCms('home'); return Array.isArray(data) ? data : Array.isArray(data?.sections) ? data.sections : []; }
export const money = (n: number) => `₹${n.toLocaleString('en-IN')}`;
