import type { Product } from '@/lib/catalog';

type ApiResponse = { success?: boolean; data?: any; message?: string; products?: any[]; items?: any[]; results?: any[]; categories?: any[] };
export type StorefrontCategory = { id:string; name:string; slug:string; imageUrl:string; description?:string; products:any[]; _count?:{products?:number} };
export type HomeCmsSection = { id:string|number; key?:string; type?:string; title?:string|null; subtitle?:string|null; imageUrl?:string|null; ctaHref?:string|null; ctaLabel?:string|null; content?:any; sortOrder?:number; sort_order?:number; isActive?:boolean; is_active?:boolean; [key:string]:any };
export type StorefrontProductOptions = { categorySlug?:string; brand?:string; size?:string; color?:string; minPrice?:number; maxPrice?:number; inStock?:boolean; sort?:string; limit?:number; page?:number; search?:string };
const BASE_URL=(process.env.PRIYASA_API_BASE_URL||'https://api.priyasa.com').replace(/\/$/,'');
async function coreFetch(path:string,init:RequestInit={}):Promise<ApiResponse>{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(`${BASE_URL}${path}`,{...init,headers:{Accept:'application/json',...(init.headers||{})},cache:'no-store',signal:init.signal||controller.signal});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message||body?.error||`PriyasaCore request failed (${response.status})`);return body||{};}finally{clearTimeout(timeout)}}
function listFrom(response:ApiResponse):any[]{const value=response?.data;if(Array.isArray(value))return value;if(Array.isArray(value?.data))return value.data;if(Array.isArray(value?.products))return value.products;if(Array.isArray(value?.items))return value.items;if(Array.isArray(value?.results))return value.results;if(Array.isArray(response?.products))return response.products;if(Array.isArray(response?.items))return response.items;if(Array.isArray(response?.results))return response.results;return []}
function mediaUrls(product:any):string[]{const sources=[product?.media,product?.images,product?.gallery,product?.image_urls];const out:string[]=[];for(const media of sources){if(Array.isArray(media))for(const item of media){const url=typeof item==='string'?item:item?.url||item?.image_url||item?.src;if(url)out.push(url)}else if(media&&typeof media==='object'){for(const item of Object.values(media)){const url=typeof item==='string'?item:(item as any)?.url||(item as any)?.image_url||(item as any)?.src;if(url)out.push(String(url))}}}return [...new Set(out)]}
function available(variant:any):number{const inventory=variant?.inventory;if(inventory)return Math.max(0,Number(inventory.available_quantity??inventory.quantity??inventory.stock??0)-Number(inventory.reserved_quantity??inventory.reserved??0));return Math.max(0,Number(variant?.available_quantity??variant?.stock??0)-Number(variant?.reserved??0))}
function mapProduct(product:any):Product{const variants=Array.isArray(product?.variants)?product.variants.filter((v:any)=>v?.is_active!==false):[];const inStock=variants.find((v:any)=>available(v)>0)||variants[0];const urls=[...mediaUrls(product),...variants.map((v:any)=>v?.image_url||v?.image).filter(Boolean)].filter((value,index,all)=>all.indexOf(value)===index);const price=Number(inStock?.selling_price??inStock?.sale_price??inStock?.price??product?.selling_price??product?.sale_price??product?.price??0);const mrp=Number(inStock?.mrp??inStock?.compare_at_price??product?.mrp??product?.compare_at_price??price);const category=product?.category;const attributes=product?.attributes||{};return{id:String(product.id),name:String(product.name||product.title||''),slug:String(product.slug||product.id),category:String(category?.name||product.category_name||'Priyasa'),categorySlug:category?.slug?String(category.slug):product.category_slug?String(product.category_slug):undefined,price,mrp,image:urls[0]||'/images/product-placeholder.svg',images:urls.length?urls:['/images/product-placeholder.svg'],colors:[...new Set(variants.map((v:any)=>v?.color||v?.color_name).filter(Boolean))] as string[],sizes:[...new Set(variants.map((v:any)=>v?.size||v?.size_name).filter(Boolean))] as string[],description:String(product?.short_description||product?.description||''),variantId:inStock?.id?String(inStock.id):'',badge:mrp>price&&price>0?`${Math.round(((mrp-price)/mrp)*100)}% OFF`:undefined,fabric:attributes.fabric||product?.fabric};}
export async function getStorefrontProducts(options:StorefrontProductOptions={}):Promise<Product[]>{const params=new URLSearchParams();if(options.categorySlug)params.set('category',options.categorySlug);if(options.brand)params.set('brand',options.brand);if(options.search)params.set('search',options.search);if(options.size)params.set('size',options.size);if(options.color)params.set('color',options.color);if(options.minPrice!=null)params.set('min_price',String(options.minPrice));if(options.maxPrice!=null)params.set('max_price',String(options.maxPrice));if(options.inStock)params.set('in_stock','1');if(options.sort)params.set('sort',options.sort);if(options.page)params.set('page',String(Math.max(1,options.page)));params.set('per_page',String(Math.min(Math.max(options.limit||24,1),100)));try{return listFrom(await coreFetch(`/api/v1/storefront/products?${params.toString()}`)).map(mapProduct)}catch{return []}}
export async function getLatestLaunches(limit=8){return getStorefrontProducts({sort:'newest',limit})}
export async function getSearchProducts(query:string,limit=24){return getStorefrontProducts({search:query,limit})}
export async function getBestSellers(limit=8){return getStorefrontProducts({sort:'popular',limit})}
export async function getSaleProducts(limit=8){return(await getStorefrontProducts({sort:'discount',limit:Math.min(100,limit*3)})).filter(p=>p.price>0&&p.mrp>p.price).slice(0,limit)}
export async function getProductsForHomeSection(type:string,limit=8):Promise<Product[]>{const t=type.toLowerCase().trim();if(t==='products-sale'||t==='sale'||t==='offer')return getSaleProducts(limit);if(t==='products-latest'||t==='latest'||t==='latest-collection'||t==='new_arrivals'||t==='new-arrivals')return getLatestLaunches(limit);if(t==='products-best'||t==='best-sellers'||t==='trending')return getBestSellers(limit);if(t.startsWith('products-category:'))return getStorefrontProducts({categorySlug:t.slice('products-category:'.length).trim(),limit});return []}
export async function getStorefrontProduct(slug:string){try{const response=await coreFetch(`/api/v1/storefront/products/${encodeURIComponent(slug)}`);const product=response.data?.product||response.data; if(!product)return null;const mapped=mapProduct(product);const variants=Array.isArray(product.variants)?product.variants.filter((v:any)=>v?.is_active!==false):[];let rating=0,reviewCount=0;try{const reviews=listFrom(await coreFetch(`/api/v1/storefront/products/${encodeURIComponent(slug)}/reviews`));reviewCount=reviews.length;rating=reviewCount?reviews.reduce((sum,review)=>sum+Number(review.rating||0),0)/reviewCount:0}catch{}return{...mapped,variants:variants.map((variant:any)=>({id:String(variant.id),color:variant.color||variant.color_name,size:variant.size||variant.size_name,price:Number(variant.selling_price??variant.sale_price??variant.price??product.price??0),mrp:Number(variant.mrp??variant.compare_at_price??product.mrp??0),stock:available(variant),sku:variant.sku})),rating,reviewCount,fabric:product?.attributes?.fabric||product?.fabric,care:product?.attributes?.care||product?.care}}catch{return null}}
export async function getStorefrontCategories():Promise<StorefrontCategory[]>{try{return listFrom(await coreFetch('/api/v1/storefront/categories')).map((category:any)=>({id:String(category.id),name:String(category.name||category.title||''),slug:String(category.slug||category.id),imageUrl:category.image_url||category.imageUrl||category.media?.url||category.image||'',description:category.description?String(category.description):undefined,products:[],_count:category._count||{products:Number(category.product_count||category.products_count||0)}}))}catch{return []}}
export async function getActiveCms(key:string){return(await coreFetch(`/api/v1/storefront/cms/${encodeURIComponent(key)}`).catch(()=>({data:null}))).data||null}
/** Home is a first-class managed resource. The API returns {version, sections[]} and is the source of truth for Home ordering/content. */
export async function getHomeCms():Promise<HomeCmsSection[]>{try{const response=await coreFetch('/api/v1/storefront/home');const sections=response?.data?.sections;return Array.isArray(sections)?sections:[]}catch{return []}}
export const money=(n:number)=>`₹${n.toLocaleString('en-IN')}`;
