import type { Product } from '@/lib/catalog';

type ApiResponse = { success?: boolean; data?: any; message?: string };
export type StorefrontCategory = { id: string; name: string; slug: string; imageUrl: string; description?: string; products: any[]; _count?: { products?: number } };
export type HomeCmsSection = { id: string; key?: string; type?: string; title?: string; subtitle?: string; imageUrl?: string; mobileImageUrl?: string; ctaHref?: string; ctaLabel?: string; sortOrder?: number; sort_order?: number; isActive?: boolean; is_active?: boolean; content?: Record<string, any>; [key: string]: any };
const BASE_URL = (process.env.PRIYASA_API_BASE_URL || 'https://api.priyasa.com').replace(/\/$/, '');
async function coreFetch(path: string, init: RequestInit = {}): Promise<ApiResponse> { const attempts = 3; let lastError: unknown; for (let attempt = 1; attempt <= attempts; attempt += 1) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 8000); try { const response = await fetch(`${BASE_URL}${path}`, { ...init, headers: { Accept: 'application/json', ...(init.headers || {}) }, cache: 'no-store', signal: init.signal || controller.signal }); const body = await response.json().catch(() => null); if (!response.ok) { const error = new Error(body?.message || `PriyasaCore request failed (${response.status})`); if (![429,502,503,504].includes(response.status) || attempt === attempts) throw error; lastError = error; await new Promise((resolve) => setTimeout(resolve, attempt * 350)); continue; } return body || {}; } catch (error) { lastError = error; if (attempt === attempts) throw error; await new Promise((resolve) => setTimeout(resolve, attempt * 350)); } finally { clearTimeout(timeout); } } throw lastError instanceof Error ? lastError : new Error('PriyasaCore request failed'); }
function listFrom(response: ApiResponse): any[] { const value = response.data; if (Array.isArray(value)) return value; if (Array.isArray(value?.data)) return value.data; return []; }
function mediaUrls(product: any): string[] { const media = product?.media; if (Array.isArray(media)) return media.map((item) => typeof item === 'string' ? item : item?.url || item?.image_url).filter(Boolean); if (media && typeof media === 'object') return Object.values(media).flatMap((item: any) => typeof item === 'string' ? [item] : [item?.url, item?.image_url]).filter(Boolean) as string[]; return []; }
function available(variant: any): number { const inventory = variant?.inventory; if (inventory) return Math.max(0, Number(inventory.quantity || 0) - Number(inventory.reserved_quantity || 0)); return Math.max(0, Number(variant?.stock || 0) - Number(variant?.reserved || 0)); }
function mapProduct(product: any): Product { const variants = Array.isArray(product?.variants) ? product.variants.filter((v: any) => v?.is_active !== false) : []; const inStock = variants.find((v: any) => available(v) > 0) || variants[0]; const urls = [...mediaUrls(product), ...variants.map((v: any) => v?.image_url).filter(Boolean)].filter((value, index, all) => all.indexOf(value) === index); const price = Number(inStock?.price ?? product?.price ?? 0); const mrp = Number(inStock?.mrp ?? product?.mrp ?? price); const category = product?.category; return { id: String(product.id), name: String(product.name || ''), slug: String(product.slug || product.product_slug || product.handle || product.id), category: String(category?.name || 'Priyasa'), categorySlug: category?.slug ? String(category.slug) : undefined, price, mrp, image: urls[0] || '/images/product-placeholder.svg', images: urls.length ? urls : ['/images/product-placeholder.svg'], colors: [...new Set(variants.map((v: any) => v?.color).filter(Boolean))] as string[], sizes: [...new Set(variants.map((v: any) => v?.size).filter(Boolean))] as string[], description: String(product?.short_description || product?.description || ''), variantId: inStock?.id ? String(inStock.id) : '', badge: mrp > price && price > 0 ? `${Math.round(((mrp - price) / mrp) * 100)}% OFF` : undefined }; }
export async function getStorefrontProducts(options: { categorySlug?: string; limit?: number; search?: string; sort?: string } = {}): Promise<Product[]> { const params = new URLSearchParams(); if (options.categorySlug) params.set('category', options.categorySlug); if (options.search) params.set('search', options.search); if (options.sort) params.set('sort', options.sort); params.set('per_page', String(Math.min(Math.max(options.limit || 24, 1), 100))); try { return listFrom(await coreFetch(`/api/v1/storefront/products?${params.toString()}`)).map(mapProduct); } catch (error) { console.warn(`[Priyasa storefront] products unavailable; rendering fallback: ${error instanceof Error ? error.message : String(error)}`); return []; } }
export async function getLatestLaunches(limit = 8, sort?: string) { return getStorefrontProducts({ limit, sort }); }
export async function getSearchProducts(query: string, limit = 24) { return getStorefrontProducts({ search: query, limit }); }
export async function getBestSellers(limit = 8, sort?: string) { return getStorefrontProducts({ limit, sort }); }
export async function getSaleProducts(limit = 8, sort?: string) { return (await getStorefrontProducts({ limit: Math.min(100, limit * 3), sort })).filter((p) => p.price > 0 && p.mrp > p.price).slice(0, limit); }
export async function getProductsForHomeSection(type: string, limit = 8, options: { sort?: string } = {}): Promise<Product[]> { const t = type.toLowerCase().trim(); if (t === 'products-sale' || t === 'sale') return getSaleProducts(limit, options.sort); if (t === 'products-latest' || t === 'latest' || t === 'latest-collection' || t === 'new_arrivals' || t === 'new-arrivals') return getLatestLaunches(limit, options.sort); if (t === 'products-best' || t === 'best-sellers' || t === 'trending') return getBestSellers(limit, options.sort); if (t.startsWith('products-category:')) return getStorefrontProducts({ categorySlug: t.slice('products-category:'.length).trim(), limit, sort: options.sort }); return []; }
export async function getStorefrontProduct(slug: string) { try { const requested = decodeURIComponent(slug); const candidates = [...new Set([requested, requested.trim(), requested.replace(/^product[-_]/i, '')])].filter(Boolean); let product: any = null; for (const candidate of candidates) { try { product = (await coreFetch(`/api/v1/storefront/products/${encodeURIComponent(candidate)}`)).data || null; if (product) break; } catch {} } if (!product) { for (const queryKey of ['slug','search']) { try { const catalog = await coreFetch(`/api/v1/storefront/products?${queryKey}=${encodeURIComponent(requested)}&per_page=100`); const items = listFrom(catalog); product = items.find((item: any) => [item?.slug,item?.product_slug,item?.handle,item?.id].filter(Boolean).some((value: any) => String(value) === requested)) || null; if (product) break; } catch {} } } if (!product) return null; const mapped = mapProduct(product); const variants = Array.isArray(product.variants) ? product.variants.filter((v: any) => v?.is_active !== false) : []; let rating = 0, reviewCount = 0; try { const reviews = listFrom(await coreFetch(`/api/v1/storefront/products/${encodeURIComponent(String(product.id))}/reviews`)); reviewCount = reviews.length; rating = reviewCount ? reviews.reduce((sum, review) => sum + Number(review.rating || 0), 0) / reviewCount : 0; } catch {} return { ...mapped, variants: variants.map((variant: any) => ({ id: String(variant.id), color: variant.color, size: variant.size, price: Number(variant.price ?? product.price ?? 0), mrp: Number(variant.mrp ?? product.mrp ?? 0), stock: available(variant), sku: variant.sku })), rating, reviewCount, fabric: product?.attributes?.fabric, care: product?.attributes?.care }; } catch (error) { console.warn(`[Priyasa storefront] product ${slug} unavailable: ${error instanceof Error ? error.message : String(error)}`); return null; } }
export async function getStorefrontCategories(): Promise<StorefrontCategory[]> { try { return listFrom(await coreFetch('/api/v1/storefront/categories')).map((category: any) => ({ id: String(category.id), name: String(category.name || ''), slug: String(category.slug || category.id), imageUrl: category.image_url || category.imageUrl || category.media?.url || '', description: category.description ? String(category.description) : undefined, products: [], _count: category._count })); } catch (error) { console.warn(`[Priyasa storefront] categories unavailable; rendering fallback: ${error instanceof Error ? error.message : String(error)}`); return []; } }
export async function getActiveCms(key: string) { return (await coreFetch(`/api/v1/storefront/cms/${encodeURIComponent(key)}`).catch(() => ({ data: null }))).data || null; }
export async function getHomeCms(): Promise<HomeCmsSection[]> { const response = await coreFetch('/api/v1/storefront/home'); const data = response?.data; const sections = Array.isArray(data?.sections) ? data.sections : Array.isArray(data) ? data : []; return sections.filter((section: any) => section && section.id != null && section.is_active !== false).sort((a:any,b:any)=>Number(a.sort_order??a.sortOrder??0)-Number(b.sort_order??b.sortOrder??0)); }
export const money = (n: number) => `₹${n.toLocaleString('en-IN')}`;
