import {db} from '@/lib/db';
import {getWooCategories,getWooProducts,getWooProductsPage,getWooVariations,type WooCategory,type WooVariation} from '@/lib/woocommerce';
const rupees=(value:string|number|null|undefined)=>{const n=Number(value||0);return Number.isFinite(n)?Math.max(0,Math.round(n)):0};
const cleanSlug=(value:string,id:number)=>{const s=value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,180);return s||`woocommerce-${id}`};
const stripHtml=(value:string)=>value.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
async function ensureCategory(c:WooCategory,cache:Map<number,string>,source:WooCategory[]):Promise<string>{const hit=cache.get(c.id);if(hit)return hit;let parentId:string|undefined;if(c.parent){const parent=source.find(x=>x.id===c.parent);if(parent)parentId=await ensureCategory(parent,cache,source)}const slug=cleanSlug(c.slug||c.name,c.id);const row=await db.category.upsert({where:{slug},create:{name:c.name,slug,description:c.description||null,imageUrl:c.image?.src||null,parentId:parentId||null},update:{name:c.name,description:c.description||null,imageUrl:c.image?.src||null,parentId:parentId||null}});cache.set(c.id,row.id);return row.id}
function variantParts(v:WooVariation){const size=v.attributes.find(a=>/size/i.test(a.name))?.option||'One Size';const color=v.attributes.find(a=>/color|colour/i.test(a.name))?.option||'Default';return {size:size.slice(0,30),color:color.slice(0,40)}}
function stockFor(quantity:number|null,inStock:boolean){if(quantity!==null&&quantity!==undefined)return Math.max(0,quantity);return inStock?9999:0}
export async function previewWooCommerceImport(){const [categories,products]=await Promise.all([getWooCategories(),getWooProducts()]);let variableProducts=0,variations=0;for(const p of products.data){if(p.type==='variable'){variableProducts++;variations+=Array.isArray(p.variations)?p.variations.length:0}}return {categories:categories.data.length,products:products.data.length,variableProducts,variations}}
async function importProduct(p:any,categorySource:WooCategory[],categoryCache:Map<number,string>){const fallback=await db.category.upsert({where:{slug:'uncategorized'},create:{name:'Uncategorized',slug:'uncategorized'},update:{}});const categoryId=p.categories[0]?await ensureCategory(categorySource.find(c=>c.id===p.categories[0].id)!,categoryCache,categorySource):fallback.id;const slug=cleanSlug(p.slug||p.name,p.id);const active=p.status==='publish'&&p.catalog_visibility!=='hidden';const mrp=rupees(p.regular_price||p.price||p.sale_price);const sale=rupees(p.sale_price||p.price||p.regular_price);const salePrice=Math.min(sale||mrp,mrp||sale);const variants=p.type==='variable'?(await getWooVariations(p.id)).data:[];let imageCount=0,variantCount=0;await db.$transaction(async tx=>{const product=await tx.product.upsert({where:{slug},create:{name:p.name,slug,description:stripHtml(p.description||p.short_description||''),categoryId,brand:null,mrp:mrp||salePrice,salePrice:salePrice||mrp,active},update:{name:p.name,description:stripHtml(p.description||p.short_description||''),categoryId,mrp:mrp||salePrice,salePrice:salePrice||mrp,active}});await tx.productImage.deleteMany({where:{productId:product.id}});if(p.images.length)await tx.productImage.createMany({data:p.images.map((i:any,index:number)=>({productId:product.id,url:i.src,alt:i.alt||i.name||p.name,sortOrder:i.position??index}))});imageCount=p.images.length;if(variants.length){for(const v of variants){const parts=variantParts(v);const sku=(v.sku||`WC-${p.id}-${v.id}`).slice(0,80);const price=rupees(v.sale_price||v.price||v.regular_price||p.sale_price||p.price||p.regular_price);const stock=stockFor(v.stock_quantity,v.in_stock);await tx.productVariant.upsert({where:{sku},create:{productId:product.id,sku,size:parts.size,color:parts.color,price:price||salePrice,stock},update:{productId:product.id,size:parts.size,color:parts.color,price:price||salePrice,stock}});variantCount++}}else{const sku=(p.sku||`WC-${p.id}`).slice(0,80);const price=salePrice||mrp;const stock=stockFor(p.stock_quantity,p.in_stock);await tx.productVariant.upsert({where:{sku},create:{productId:product.id,sku,size:'One Size',color:'Default',price,stock},update:{productId:product.id,size:'One Size',color:'Default',price,stock}});variantCount++}const rawMetadata={source:'woocommerce',wooProductId:p.id,name:p.name,attributes:p.attributes||[],tags:p.tags||[],weight:p.weight||null,dimensions:p.dimensions||null,featured:!!p.featured};await tx.settings.upsert({where:{key:`woo.product.${slug}`},create:{key:`woo.product.${slug}`,value:rawMetadata},update:{value:rawMetadata}})});return {slug,imageCount,variantCount}}
export async function importWooCommercePage(page=1,perPage=10){const [categories,products]=await Promise.all([getWooCategories(),getWooProductsPage(page,perPage)]);const cache=new Map<number,string>();for(const c of categories.data)await ensureCategory(c,cache,categories.data);let imported=0,skipped=0,images=0,variants=0;const slugs:string[]=[];for(const p of products.data){try{const r=await importProduct(p,categories.data,cache);imported++;slugs.push(r.slug);images+=r.imageCount;variants+=r.variantCount}catch(error){skipped++;console.error(`WooCommerce product ${p.id} import failed`,error)}}return {page,totalPages:products.totalPages,totalProducts:products.total,imported,skipped,images,variants,slugs,hasMore:page<products.totalPages}}
export async function finalizeWooCommerceSync(slugs:string[]){if(!slugs.length)throw new Error('No imported products were supplied for sync finalization');const stale=await db.product.updateMany({where:{slug:{notIn:slugs}},data:{active:false}});return {deactivatedStaleProducts:stale.count}}
export async function importWooCommerceCatalog(options:{sync?:boolean}={}){const preview=await previewWooCommerceImport();let page=1,totalImported=0,totalSkipped=0,totalImages=0,totalVariants=0;const slugs:string[]=[];do{const r=await importWooCommercePage(page,10);totalImported+=r.imported;totalSkipped+=r.skipped;totalImages+=r.images;totalVariants+=r.variants;slugs.push(...r.slugs);page++}while(page<=Math.ceil(preview.products/10));const deactivatedStaleProducts=options.sync&&totalSkipped===0?(await finalizeWooCommerceSync(slugs)).deactivatedStaleProducts:0;return {categories:preview.categories,products:totalImported,variants:totalVariants,images:totalImages,skipped:totalSkipped,deactivatedStaleProducts}}
export async function syncWooCommerceCatalog(){return importWooCommerceCatalog({sync:true})}
