'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import ReturnRequest from '@/components/ReturnRequest';
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN')}`;const label=(s:string)=>String(s||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
export default function OrderDetail({params}:{params:Promise<{id:string}>}){
 const [order,setOrder]=useState<any>();const [error,setError]=useState('');const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
 async function load(){try{const p=await params;const r=await fetch(`/api/customer/orders/${encodeURIComponent(p.id)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load order');setOrder(d.data)}catch(e){setError(e instanceof Error?e.message:'Unable to load order')}}
 useEffect(()=>{void load()},[params]);
 async function cancelOrder(){if(!order||busy)return;if(!window.confirm('Cancel this order? This action cannot be undone.'))return;setBusy('cancel');setMessage('Cancelling order securely…');try{const r=await fetch(`/api/customer/orders/${encodeURIComponent(order.id)}/cancel`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to cancel order');setMessage('Order cancelled successfully.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to cancel order')}finally{setBusy('')}}
 async function invoice(){if(!order||busy)return;setBusy('invoice');setMessage('Preparing invoice…');try{const r=await fetch(`/api/customer/orders/${encodeURIComponent(order.id)}/invoice`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Invoice is not available yet.');const value=d?.invoice_url||d?.url||d?.download_url||d?.data?.invoice_url||d?.data?.url||d?.data?.download_url;if(value){window.open(value,'_blank','noopener,noreferrer');setMessage('Invoice opened in a new tab.')}else{setMessage('Invoice is available from order support, but no downloadable URL was returned.')}}catch(e){setMessage(e instanceof Error?e.message:'Unable to load invoice')}finally{setBusy('')}}
 if(error)return <div className="account-shell"><div className="account-card"><h2>{error}</h2><Link className="button" href="/login">Sign in</Link></div></div>;
 if(!order)return <div className="account-shell"><div className="account-orders-loading">Loading order…</div></div>;
 const returnExisting=order.returns?.[0]||null;const status=String(order.status||'').toUpperCase();const canCancel=['CREATED','PAYMENT_PENDING','CONFIRMED','PROCESSING'].includes(status);const eligible=status==='DELIVERED'&&!returnExisting&&(Date.now()-new Date(order.deliveredAt||order.updatedAt||order.createdAt).getTime()<30*24*60*60*1000);const canInvoice=['CONFIRMED','PROCESSING','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','COMPLETED'].includes(status);
 return <div className="account-shell"><div className="breadcrumbs"><Link href="/account/orders">My Orders</Link><span> / </span>{order.orderNumber}</div><div className="account-main-head"><div><span className="eyebrow">ORDER DETAILS</span><h1>{order.orderNumber}</h1><p className="account-lead">Placed {new Date(order.createdAt).toLocaleString('en-IN')}</p></div><span className="order-status">{label(status)}</span></div>
 <div className="order-action-bar">{(status==='PAYMENT_PENDING'||status==='CREATED')&&<Link className="button" href={`/checkout/payment/${encodeURIComponent(order.id)}`}>Pay Now</Link>}{canCancel&&<button className="button button-light" disabled={!!busy} onClick={cancelOrder}>{busy==='cancel'?'Cancelling…':'Cancel Order'}</button>}{canInvoice&&<button className="button button-light" disabled={!!busy} onClick={invoice}>{busy==='invoice'?'Preparing…':'View Invoice'}</button>}<Link className="button button-light" href={`/track-order?order=${encodeURIComponent(order.orderNumber)}`}>Track Order</Link></div>
 {message&&<div className="checkout-status" role="status">{message}</div>}
 <div className="order-detail-grid"><section className="account-card"><h2>Items</h2>{order.items.map((i:any)=><div className="detail-item" key={i.id}><div className="order-item-image">{i.variant?.product?.images?.[0]?.url&&<img src={i.variant.product.images[0].url} alt=""/>}</div><div><strong>{i.productName}</strong><small>{i.color||'—'} · {i.size||'—'} · Qty {i.quantity}</small><b>{money(i.unitPrice*i.quantity)}</b></div></div>)}</section><aside className="account-card"><h2>Order summary</h2><div className="summary-lines"><div><span>Subtotal</span><strong>{money(order.subtotal)}</strong></div><div><span>Discount</span><strong>-{money(order.discount)}</strong></div><div><span>Shipping</span><strong>{order.shipping?money(order.shipping):'Free'}</strong></div>{order.tax!=null&&<div><span>Tax</span><strong>{money(order.tax)}</strong></div>}<hr/><div className="cart-total"><span>Total</span><strong>{money(order.total)}</strong></div></div>{order.address&&<div className="order-address"><strong>Delivery address</strong><p>{order.address.fullName||order.address.recipient_name}<br/>{order.address.line1}<br/>{order.address.city}, {order.address.state} - {order.address.pincode||order.address.postal_code}</p></div>}</aside></div>
 <section className="account-card order-timeline"><h2>Order timeline</h2>{(order.statusHistory||[]).map((h:any)=><div key={h.id} className="timeline-row"><b>✓</b><div><strong>{label(h.toStatus)}</strong><small>{new Date(h.createdAt).toLocaleString('en-IN')}</small>{h.note&&<span>{h.note}</span>}</div></div>)}{order.shipment&&<div className="shipment-box"><strong>Shipment</strong><p>{order.shipment.carrier||'Carrier assigned'} {order.shipment.trackingNumber?`· ${order.shipment.trackingNumber}`:''}</p>{order.shipment.trackingUrl&&<a href={order.shipment.trackingUrl} target="_blank" rel="noreferrer">Track shipment →</a>}</div>}<ReturnRequest orderId={order.id} eligible={eligible} existing={returnExisting}/></section>
 </div>}
