import Link from 'next/link';
import { cookies } from 'next/headers';
import { ShieldIcon, CreditCardIcon, UpiIcon, WalletIcon } from '@/components/StorefrontIcons';

export default async function PaymentMethodsPage(){
  const jar=await cookies();
  const authenticated=Boolean(jar.get('priyasa_local_user_id')?.value||jar.get('priyasa_mobile')?.value);
  if(!authenticated)return <div className="storefront-page"><div className="page storefront-inner account-subpage"><span className="eyebrow">MY PRIYASA</span><h1>Payment Methods</h1><p className="account-lead">Sign in with your mobile number to manage your checkout preferences.</p><Link className="button dark-button" href="/login">Continue with Mobile</Link></div></div>;
  return <div className="storefront-page"><div className="page storefront-inner account-subpage payment-methods-page"><div className="breadcrumbs"><Link href="/account">My Account</Link> / Payment Methods</div><div className="account-main-head"><div><span className="eyebrow">ACCOUNT PAYMENTS</span><h1>Payment Methods</h1><p className="account-lead">Your payment details stay with the secure payment provider. Priyasa does not store card numbers or UPI credentials.</p></div><ShieldIcon/></div><div className="account-card"><div className="account-section-title"><div><span className="eyebrow">SECURE CHECKOUT</span><h2>Choose a payment method at checkout</h2></div></div><div className="quick-links payment-methods-options"><div className="quick-link"><CreditCardIcon width={22} height={22}/><strong>Cards & Net Banking</strong><small>Pay securely through Razorpay</small></div><div className="quick-link"><UpiIcon width={22} height={22}/><strong>UPI</strong><small>Google Pay, PhonePe and supported UPI apps</small></div><div className="quick-link"><WalletIcon width={22} height={22}/><strong>Priyasa Wallet</strong><small>Use available wallet balance</small></div></div><Link className="button dark-button" href="/cart">Continue shopping</Link></div><div className="checkout-assurance"><strong>Security first.</strong> Payment credentials are entered in the secure gateway flow. We never ask you to share an OTP, PIN or card CVV with customer support.</div></div></div>;
}
