'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import styles from '../admin-modern.module.css';

type Segment={key:string;name:string;description:string;count:number|null};
type Automation={id:string;name:string;trigger:string;enabled:boolean;conditions?:{segment?:string};runs?:unknown[]};
const presets=[
 ['abandoned_cart','Abandoned cart recovery','cart_activity',['SEND_EMAIL','SEND_WHATSAPP']],
 ['first_order','First-order offer','buyers',['SEND_EMAIL']],
 ['repeat_buyer','Repeat customer','repeat_buyers',['SEND_WHATSAPP']],
 ['winback','Win-back campaign','delivered_buyers',['SEND_EMAIL','SEND_WHATSAPP']]
] as const;
export default function MarketingAutomation(){
 const [segments,setSegments]=useState<Segment[]>([]);const [rules,setRules]=useState<Automation[]>([]);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const [q,setQ]=useState('');
 async function load(){try{const [s,a]=await Promise.all([fetch('/api/admin/marketing/segments',{cache:'no-store'}),fetch('/api/admin/automations',{cache:'no-store'})]);const sd=await s.json(),ad=await a.json();if(s.ok)setSegments(sd.data||[]);if(a.ok)setRules(ad.data||[]);else setMsg(ad.error||'Unable to load automations')}catch(e){setMsg(e instanceof Error?e.message:'Unable to load growth data')}}
 useEffect(()=>{void load()},[]);
 const enabled=rules.filter(x=>x.enabled).length;const runs=rules.reduce((n,x)=>n+(x.runs?.length||0),0);const audience=useMemo(()=>segments.reduce((n,s)=>n+(s.count||0),0),[segments]);
 const visible=rules.filter(x=>!q||x.name.toLowerCase().includes(q.toLowerCase())||x.trigger.toLowerCase().includes(q.toLowerCase()));
 async function create(p:(typeof presets)[number]){setBusy(true);setMsg('');try{const r=await fetch('/api/admin/automations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:p[1],trigger:p[0],conditions:{segment:p[2]},actions:p[3].map(action=>({type:action,templateKey:p[0]})),enabled:true})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to create automation');setMsg(`${p[1]} automation created.`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Unable to create automation')}finally{setBusy(false)}}
 return <div className={styles.shell}><aside className={styles.side}><div className={styles.brand}><div className={styles.brandMark}>P</div><div className={styles.brandText}>PRIYASA<span>Commerce OS</span></div></div><div className={styles.navTitle}>GROWTH</div><nav className={styles.nav}><Link href="/admin">Overview</Link><Link href="/admin/customers">Customers</Link><Link href="/admin/promotions">Promotions</Link><Link className={styles.active} href="/admin/marketing-automation">Automation</Link><Link href="/admin/automations">Workflow engine</Link><Link href="/admin/analytics">Analytics</Link></nav></aside>
 <main className={styles.main}><header className={styles.top}><div className={styles.search}>⌕ <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search workflows…"/></div><div className={styles.topSpacer}/><button className={styles.secondary} onClick={()=>void load()}>↻ Refresh</button><Link className={styles.topLink} href="/admin">Dashboard</Link><div className={styles.avatar}>A</div></header>
 <div className={styles.content}><div className={styles.head}><div><div className={styles.kicker}>GROWTH ENGINE · LIFECYCLE</div><h1>Marketing automation</h1><p>Turn customer signals into controlled, repeatable retention workflows across email and WhatsApp.</p></div><div className={styles.headActions}><Link className={styles.secondary} href="/admin/customers">Customer 360</Link><Link className={styles.primary} href="/admin/automations">Open workflow engine →</Link></div></div>
 {msg&&<div className={styles.quick}><strong>Automation update</strong><span>{msg}</span></div>}
 <div className={styles.stats}><div className={styles.stat}><div className={styles.statTop}><span className={styles.statLabel}>Audience signals</span><span className={styles.statIcon}>◎</span></div><div className={styles.statValue}>{audience.toLocaleString('en-IN')}</div><div className={styles.statMeta}>Across available segments</div></div><div className={styles.stat}><div className={styles.statTop}><span className={styles.statLabel}>Active workflows</span><span className={styles.statIcon}>↗</span></div><div className={styles.statValue}>{enabled}</div><div className={styles.statMeta}>{rules.length} configured</div></div><div className={styles.stat}><div className={styles.statTop}><span className={styles.statLabel}>Recent runs</span><span className={styles.statIcon}>◇</span></div><div className={styles.statValue}>{runs}</div><div className={styles.statMeta}>Returned by automation API</div></div><div className={styles.stat}><div className={styles.statTop}><span className={styles.statLabel}>Channels</span><span className={styles.statIcon}>✦</span></div><div className={styles.statValue}>2</div><div className={styles.statMeta}>Email + WhatsApp</div></div></div>
 <section className={styles.section}><div className={styles.panelHead}><div><h2>Customer signal map</h2><p>Live audience definitions from the authenticated segmentation API.</p></div><span className={styles.pill}>{segments.length} segments</span></div><div className={styles.stats}>{segments.map(s=><div className={styles.stat} key={s.key}><div className={styles.statTop}><span className={styles.statLabel}>{s.name}</span><span className={styles.statIcon}>●</span></div><div className={styles.statValue}>{s.count===null?'Dynamic':s.count.toLocaleString('en-IN')}</div><div className={styles.statMeta}>{s.description}</div></div>)}</div></section>
 <section className={styles.section}><div className={styles.panelHead}><div><h2>Launch a lifecycle playbook</h2><p>Preconfigured recipes create rules through the existing automation engine.</p></div></div><div className={styles.quick}>{presets.map(p=><article key={p[0]} style={{flex:'1 1 220px',padding:18,border:'1px solid var(--admin-line)',borderRadius:18,background:'#fff'}}><div className={styles.kicker}>{p[0].replaceAll('_',' ')}</div><h3>{p[1]}</h3><p>{segments.find(s=>s.key===p[2])?.name||p[2]} · {p[3].join(' + ')}</p><button className={styles.primary} disabled={busy} onClick={()=>void create(p)}>{busy?'Working…':'Create workflow'}</button></article>)}</div></section>
 <section className={styles.section}><div className={styles.panelHead}><div><h2>Workflow portfolio</h2><p>Search, inspect and hand off to the full workflow engine for deeper controls.</p></div><span className={styles.pill}>{visible.length} shown</span></div>{visible.length?<div className={styles.table}><table><thead><tr><th>Workflow</th><th>Trigger</th><th>Audience</th><th>Status</th><th>Runs</th><th>Manage</th></tr></thead><tbody>{visible.map(a=><tr key={a.id}><td><strong>{a.name}</strong></td><td>{a.trigger}</td><td>{a.conditions?.segment||'All customers'}</td><td><span className={styles.pill}>{a.enabled?'ENABLED':'PAUSED'}</span></td><td>{a.runs?.length||0}</td><td><Link className={styles.secondary} href="/admin/automations">Open engine</Link></td></tr>)}</tbody></table></div>:<div className={styles.quick}>No matching workflows found.</div>}</section>
 <div className={styles.footerNote}>Provider delivery remains decoupled: this workspace creates and manages automation rules; provider adapters handle actual email/WhatsApp delivery.</div>
 </div></main></div>;
}
