'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';

type Branding={siteTitle:string;headerDesktopLogo:string;headerMobileLogo:string;footerDesktopLogo:string;footerMobileLogo:string};
const defaults:Branding={siteTitle:'PRIYASA — Every You, Beautiful',headerDesktopLogo:'/images/priyasa-logo.svg',headerMobileLogo:'/images/priyasa-icon.svg',footerDesktopLogo:'/images/priyasa-logo.svg',footerMobileLogo:'/images/priyasa-icon.svg'};

export default function Settings(){
 const [data,setData]=useState<any>({roles:[],permissions:[],staff:[]});
 const [role,setRole]=useState({name:'Catalog Manager',description:'Manage products and inventory',permissions:['products.read','products.write','inventory.write']});
 const [assign,setAssign]=useState({phone:'',roleId:'',role:'STAFF'});
 const [branding,setBranding]=useState<Branding>(defaults);const[msg,setMsg]=useState('');const[savingBranding,setSavingBranding]=useState(false);
 useEffect(()=>{fetch('/api/admin/roles').then(r=>r.json()).then(d=>{setData(d);if(d.roles?.[0])setAssign(x=>({...x,roleId:d.roles[0].id}))});fetch('/api/admin/store-settings').then(r=>r.json()).then(d=>{if(d.data)setBranding({...defaults,...d.data})})},[]);
 async function saveRole(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/roles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(role)});const d=await r.json();setMsg(r.ok?'Role saved':d.error||'Unable to save');if(r.ok)location.reload()}
 async function assignRole(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/roles/assign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(assign)});const d=await r.json();setMsg(r.ok?'Role assigned':d.error||'Unable to assign')}
 async function saveBranding(e:React.FormEvent){e.preventDefault();setSavingBranding(true);const r=await fetch('/api/admin/store-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(branding)});const d=await r.json();setMsg(r.ok?'Storefront branding saved. Refresh the storefront to see the new assets.':d.error||'Unable to save branding');if(r.ok)setBranding({...defaults,...d.data});setSavingBranding(false)}
 const field=(key:keyof Branding,label:string,help:string)=><label><span>{label}</span><input className="input" value={branding[key]} onChange={e=>setBranding(x=>({...x,[key]:e.target.value}))}/><small className="muted">{help}</small></label>;
 return <div className="admin-shell"><aside className="admin-nav"><h2>PRIYASA Admin</h2><Link href="/admin">← Dashboard</Link><Link href="/admin/settings">Settings</Link><Link href="/admin/coupons-offers">Offers & Coupons</Link></aside><section className="admin-main"><h1>Settings & Permissions</h1><p className="muted">Control staff permissions and the storefront brand identity without changing code.</p>{msg&&<div className="checkout-status">{msg}</div>}
 <form className="admin-card" onSubmit={saveBranding} style={{marginTop:18}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'flex-start',flexWrap:'wrap'}}><div><span className="eyebrow dark">STOREFRONT</span><h2>Branding & browser title</h2><p className="muted">Use absolute URLs or paths from <code>/public</code>. Desktop and mobile assets are controlled separately.</p></div><button className="button dark-button" disabled={savingBranding}>{savingBranding?'Saving…':'Save storefront settings'}</button></div><div className="feature-grid" style={{marginTop:18}}>{field('siteTitle','Site / browser title','Used as the default storefront title. Example: PRIYASA — Every You, Beautiful.')}{field('headerDesktopLogo','Header desktop logo','Recommended: wide wordmark, SVG or WebP.')}{field('headerMobileLogo','Header mobile logo','Recommended: compact icon, SVG or WebP.')}{field('footerDesktopLogo','Footer desktop logo','Recommended: wide wordmark, SVG or WebP.')}{field('footerMobileLogo','Footer mobile logo','Recommended: compact icon, SVG or WebP.')}</div><div className="admin-branding-preview"><div><strong>Header preview</strong><img src={branding.headerDesktopLogo} alt="Header desktop logo preview"/><img src={branding.headerMobileLogo} alt="Header mobile logo preview"/></div><div><strong>Footer preview</strong><img src={branding.footerDesktopLogo} alt="Footer desktop logo preview"/><img src={branding.footerMobileLogo} alt="Footer mobile logo preview"/></div></div></form>
 <div className="feature-grid" style={{marginTop:18}}><form className="admin-card" onSubmit={saveRole}><h2>Create / update role</h2><label>Name<input className="input" value={role.name} onChange={e=>setRole(x=>({...x,name:e.target.value}))}/></label><label>Description<input className="input" value={role.description} onChange={e=>setRole(x=>({...x,description:e.target.value}))}/></label><div className="push-consent">{data.permissions.map((p:any)=><label key={p.key}><input type="checkbox" checked={role.permissions.includes(p.key)} onChange={e=>setRole(x=>({...x,permissions:e.target.checked?[...new Set([...x.permissions,p.key])]:x.permissions.filter(k=>k!==p.key)}))}/> {p.key}</label>)}</div><button className="button dark-button">Save Role</button></form><form className="admin-card" onSubmit={assignRole}><h2>Assign staff role</h2><label>Staff phone<input className="input" required value={assign.phone} onChange={e=>setAssign(x=>({...x,phone:e.target.value}))}/></label><label>Role<select className="input" value={assign.roleId} onChange={e=>setAssign(x=>({...x,roleId:e.target.value}))}>{data.roles.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Account type<select className="input" value={assign.role} onChange={e=>setAssign(x=>({...x,role:e.target.value}))}><option value="STAFF">Staff</option><option value="ADMIN">Admin</option></select></label><button className="button dark-button">Assign</button></form></div><h2 style={{marginTop:28}}>Current staff</h2><table className="table"><thead><tr><th>Name</th><th>Phone</th><th>Account</th><th>Role</th></tr></thead><tbody>{data.staff.map((u:any)=><tr key={u.id}><td>{u.name||'—'}</td><td>{u.phone}</td><td>{u.role}</td><td>{data.roles.find((r:any)=>r.id===u.adminRoleId)?.name||'—'}</td></tr>)}</tbody></table></section></div>}
