'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { money } from '@/lib/catalog';
type Item={variantId:string;productId:string;name:string;price:number;quantity:number;image?:string};
export default function Cart(){
 const [items,setItems]=useState<Item[]>([]); const [coupon,setCoupon]=useState(''); const [applied,setApplied]=useState(false);
 useEffect(()=>{const load=()=>setItems(JSON.parse(localStorage.getItem('priyasa_cart')||'[]'));load();window.addEventListener('priyasa-cart-updated',load);return()=>window.removeEventListener('priyasa-cart-updated',load)},[]);
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+i.price*i.quantity,0),[items]); const discount=(applied||subtotal>=2499)?500:0; const shipping=subtotal>=999?0:99; const total=Math.max(0,subtotal-discount+shipping); const remaining=Math.max(0,999-subtotal);
 function save(next:Item[]){setItems(next);localStorage.setItem('priyasa_cart',JSON.stringify(next));window.dispatchEvent(new Event('priyasa-cart-updated'))}
 return <div className="storefront-page"><div className="page storefront-inner cart-page"><div className="breadcrumbs"><Link href="/">Home</Link> / Cart</div><div className="cart-heading"><div><span className="eyebrow dark">YOUR EDIT</span><h1>Shopping bag</h1></div><span>{items.length} {items.length===1?'item':'items'}</span></div>
 {items.length===0?<div className="empty-cart"><div className="empty-cart-icon">▢</div><h2>Your bag is waiting</h2><p>Discover something beautiful and add it to your Priyasa edit.</p><Link className="button dark-button" href="/shop">Continue shopping</Link></div>:<><div className="cart-layout"><section className="cart-items"><div className="cart-benefit">{remaining>0?<><strong>Almost there.</strong> Add {money(remaining)} more for free shipping.</>:<><strong>Free shipping unlocked.</strong> Your order qualifies for complimentary delivery.</>}</div>{items.map((i,idx)=><article className="cart-product" key={i.variantId}><div className="cart-product-image">{i.image?<Image src={i.image} alt={i.name} width={180} height={230}/>:<div/>}</div><div className="cart-product-info"><div><span className="product-category">PRIYASA</span><h3>{i.name}</h3><p>{money(i.price)}</p></div><button className="cart-remove" onClick={()=>save(items.filter((_,j)=>j!==idx))}>Remove</button><div className="cart-product-bottom"><div className="qty-control"><button onClick={()=>{const n=[...items];n[idx].quantity=Math.max(1,n[idx].quantity-1);save(n)}}>−</button><span>{i.quantity}</span><button onClick={()=>{const n=[...items];n[idx].quantity++;save(n)}}>+</button></div><strong>{money(i.price*i.quantity)}</strong></div></div></article>)}<Link className="continue-shopping" href="/shop">← Continue shopping</Link></section><aside className="cart-summary"><h2>Order summary</h2><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div><span>Discount</span><strong className="green">-{money(discount)}</strong></div><div><span>Shipping</span><strong>{shipping?'₹99':'Free'}</strong></div><hr/><div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><label className="coupon-box"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Coupon code"/><button onClick={()=>setApplied(!!coupon.trim())}>Apply</button></label>{applied&&<small className="green">Coupon applied</small>}<Link className="button dark-button cart-checkout" href="/checkout">Proceed to checkout</Link><p className="summary-note">Secure checkout · Easy returns · WhatsApp support</p></aside></div></>}
 </div></div>;
}
