'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';

type Address={id:string;fullName:string;phone:string;line1:string;city:string;state:string;pincode:string;isDefault?:boolean;label?:string};
const empty={fullName:'',phone:'',line1:'',city:'',state:'',pincode:'',isDefault:false};

export default function Addresses(){
  const [addresses,setAddresses]=useState<Address[]>([]),[form,setForm]=useState(empty),[adding,setAdding]=useState(false),[editing,setEditing]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[removing,setRemoving]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
  async function load(){setLoading(true);setError('');try{const r=await fetch('/api/customer/addresses',{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to load saved addresses.');setAddresses(Array.isArray(d.data)?d.data:[])}catch(e){setError(e instanceof Error?e.message:'Unable to load saved addresses.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  function update(k:keyof typeof empty,v:string|boolean){setForm(f=>({...f,[k]:v}))}
  function startEdit(a:Address){setEditing(a.id);setAdding(false);setForm({fullName:a.fullName||'',phone:a.phone||'',line1:a.line1||'',city:a.city||'',state:a.state||'',pincode:a.pincode||'',isDefault:Boolean(a.isDefault)}) ;setMessage('')}
  function reset(){setForm(empty);setAdding(false);setEditing('');setMessage('')}
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');try{const payload={...form,phone:form.phone.replace(/\D/g,''),pincode:form.pincode.replace(/\D/g,'')};const r=await fetch('/api/customer/addresses',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{id:editing,...payload}:payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to save address.');setMessage(editing?'Address updated successfully.':'Address saved successfully.');reset();await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save address.')}finally{setSaving(false)}}
  async function remove(id:string){if(!window.confirm('Remove this saved address?'))return;setRemoving(id);setError('');try{const r=await fetch(`/api/customer/addresses?id=${encodeURIComponent(id)}`,{method:'DELETE'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to remove address.');setMessage('Address removed.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to remove address.')}finally{setRemoving('')}}
  return <div className="account-shell">
    <div className="breadcrumbs"><Link href="/account">My Account</Link><span> / </span> Addresses</div>
    <div className="account-main-head"><div><span className="eyebrow">MY PRIYASA</span><h1>Saved Addresses</h1><p className="muted">Manage delivery addresses for faster checkout.</p></div><button className="button" onClick={()=>{if(adding||editing)reset();else setAdding(true)}}>{adding||editing?'Close':'Add New Address'}</button></div>
    {message&&<div className="checkout-status" role="status">{message}</div>}{error&&<div className="checkout-status error" role="alert">{error}</div>}
    {(adding||editing)&&<form className="account-card form-grid address-editor" onSubmit={save}>
      <div className="address-editor-head"><div><span className="eyebrow">{editing?'EDIT ADDRESS':'NEW ADDRESS'}</span><h2>{editing?'Update delivery address':'Add delivery address'}</h2></div><span className="address-secure">✓ Securely saved to your account</span></div>
      {([['fullName','Full Name'],['phone','Phone'],['line1','Address'],['city','City'],['state','State'],['pincode','Pincode']] as const).map(([k,l])=><label className={k==='line1'?'full-span':''} key={k}>{l}<input className="input" required value={form[k] as string} inputMode={k==='phone'||k==='pincode'?'numeric':undefined} maxLength={k==='pincode'?6:120} onChange={e=>update(k,k==='phone'||k==='pincode'?e.target.value.replace(/\D/g,''):e.target.value)}/></label>)}
      <label className="address-default"><input type="checkbox" checked={form.isDefault} onChange={e=>update('isDefault',e.target.checked)}/> Make this my default address</label>
      <div className="address-editor-actions"><button className="button button-light" type="button" disabled={saving} onClick={reset}>Cancel</button><button className="button" disabled={saving} type="submit">{saving?'Saving…':editing?'Update Address':'Save Address'}</button></div>
    </form>}
    <div className="address-list">{loading?<div className="account-card order-empty"><h2>Loading addresses…</h2><p>Please wait while we load your saved delivery addresses.</p></div>:addresses.map(a=><article className={`account-card saved-address-card ${a.isDefault?'is-default':''}`} key={a.id}><div className="saved-address-content"><div className="saved-address-top"><span className="eyebrow">{a.isDefault?'DEFAULT ADDRESS':'SAVED ADDRESS'}</span>{a.isDefault&&<span className="address-home-chip">HOME</span>}</div><h2>{a.fullName}</h2><p>{a.line1}<br/>{a.city}, {a.state} - {a.pincode}</p><small>{a.phone}</small></div><div className="saved-address-actions"><button className="button button-light" disabled={Boolean(removing)||saving} onClick={()=>startEdit(a)}>Edit</button><button className="button button-light danger-text" disabled={removing===a.id||saving} onClick={()=>remove(a.id)}>{removing===a.id?'Removing…':'Remove'}</button></div></article>)}{!addresses.length&&!adding&&!editing&&!loading&&<div className="account-card order-empty"><h2>No saved addresses</h2><p>Add an address once and it will be available directly during checkout.</p><button className="button" onClick={()=>setAdding(true)}>Add New Address</button></div>}</div>
  </div>
}
