'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';

type Address={id:string|number;label?:string|null;recipient_name:string;phone:string;line1:string;line2?:string|null;area?:string|null;city:string;state:string;postal_code:string;landmark?:string|null;is_default:boolean};
const empty={label:'',recipient_name:'',phone:'',line1:'',line2:'',area:'',city:'',state:'',postal_code:'',landmark:'',is_default:false};

export default function Addresses(){
  const [addresses,setAddresses]=useState<Address[]>([]),[form,setForm]=useState({...empty}),[editing,setEditing]=useState<string|number|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const load=()=>fetch('/api/customer/addresses',{cache:'no-store'}).then(r=>r.json()).then(d=>setAddresses(Array.isArray(d.data)?d.data:[]));
  useEffect(()=>{load()},[]);
  const update=(k:string,v:any)=>setForm(f=>({...f,[k]:v}));
  function startEdit(a:Address){setEditing(a.id);setForm({...empty,...a});setMessage('');}
  function startAdd(){setEditing(null);setForm({...empty});setMessage('');}
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('Saving…');try{const payload={...form};const r=await fetch('/api/customer/addresses',{method:editing===null?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing===null?payload:{...payload,id:String(editing)})});const d=await r.json();if(!r.ok){setMessage(d.error||'Unable to save address');return}setForm({...empty});setEditing(null);setMessage('Address saved.');await load()}finally{setBusy(false)}}
  async function remove(id:string|number){if(!window.confirm('Remove this address?'))return;setBusy(true);try{await fetch(`/api/customer/addresses?id=${encodeURIComponent(String(id))}`,{method:'DELETE'});await load()}finally{setBusy(false)}}
  async function makeDefault(id:string|number){setBusy(true);try{const r=await fetch('/api/customer/addresses',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:String(id),is_default:true})});if(!r.ok){const d=await r.json().catch(()=>null);setMessage(d?.error||'Unable to update default address');return}await load()}finally{setBusy(false)}}
  return <div className="account-shell"><div className="breadcrumbs"><Link href="/account">My Account</Link><span> / </span> Addresses</div><div className="account-main-head"><div><span className="eyebrow">MY PRIYASA</span><h1>Saved Addresses</h1></div><button className="button" onClick={()=>editing===null&&form.recipient_name?setForm({...empty}):startAdd()}>{editing===null&&form.recipient_name?'Reset':'Add New Address'}</button></div>
    {(editing!==null||form.recipient_name||addresses.length===0)&&<form className="account-card form-grid" onSubmit={save}>{[['recipient_name','Full Name'],['phone','Phone'],['line1','Address'],['line2','Address line 2'],['area','Area / Locality'],['city','City'],['state','State'],['postal_code','Pincode'],['landmark','Landmark']].map(([k,l])=><label className={k==='line1'||k==='line2'||k==='landmark'?'full-span':''} key={k}>{l}<input className="input" required={['recipient_name','phone','line1','city','state','postal_code'].includes(k)} value={(form as any)[k]} maxLength={k==='postal_code'?6:undefined} onChange={e=>update(k,k==='postal_code'?e.target.value.replace(/\D/g,'').slice(0,6):e.target.value)}/></label>)}<label className="address-default"><input type="checkbox" checked={form.is_default} onChange={e=>update('is_default',e.target.checked)}/> Make default</label><div className="form-actions"><button className="button" disabled={busy} type="submit">{busy?'Saving…':editing===null?'Save Address':'Update Address'}</button>{editing!==null&&<button type="button" className="button button-light" onClick={startAdd}>Cancel</button>}</div></form>}
    {message&&<div className="checkout-status">{message}</div>}<div className="address-list">{addresses.map(a=><article className="account-card saved-address-card" key={a.id}><div><span className="eyebrow">{a.is_default?'DEFAULT ADDRESS':'SAVED ADDRESS'}</span><h2>{a.recipient_name}</h2><p>{a.line1}{a.line2&&<><br/>{a.line2}</>}<br/>{a.city}, {a.state} - {a.postal_code}</p><small>{a.phone}</small></div><div className="form-actions"><button disabled={busy} className="button button-light" onClick={()=>startEdit(a)}>Edit</button>{!a.is_default&&<button disabled={busy} className="button button-light" onClick={()=>makeDefault(a.id)}>Make default</button>}<button disabled={busy} className="button button-light" onClick={()=>remove(a.id)}>Remove</button></div></article>)}{!addresses.length&&!form.recipient_name&&<div className="account-card order-empty"><h2>No saved addresses</h2><p>Add an address for a faster checkout.</p></div>}</div></div>
}
