import Link from 'next/link';import {db} from '@/lib/db';import {getSession} from '@/lib/auth';import {redirect} from 'next/navigation';import {money} from '@/lib/catalog';import AdminOrderActions from '@/components/AdminOrderActions';import AdminBulkOrderActions from '@/components/AdminBulkOrderActions';

export default async function OrdersAdmin({searchParams}:{searchParams?:Promise<{q?:string;status?:string}>}){
 const s=await getSession();if(!s||!['ADMIN','STAFF'].includes(s.role))redirect('/admin/login');
 const params=await searchParams;const q=(params?.q||'').trim();const status=params?.status||'';
 const where:any={};
 if(status)where.status=status;
 if(q)where.OR=[{orderNumber:{contains:q,mode:'insensitive'}},{user:{phone:{contains:q,mode:'insensitive'}}},{user:{name:{contains:q,mode:'insensitive'}}}];
 const rows=await db.order.findMany({where,include:{user:true,payment:true,items:true,shipment:true},orderBy:{createdAt:'desc'},take:100});
 return <div className="admin-orders-reference"><div className="admin-shell"><aside className="admin-nav"><h2>PRIYASA</h2><Link href="/admin">← Dashboard</Link><Link href="/admin/orders">Orders</Link><Link href="/admin/orders/new">Manual Order</Link><Link href="/admin/products">Products</Link><Link href="/admin/inventory">Inventory</Link><Link href="/admin/returns-refunds">Returns & Refunds</Link></aside><section className="admin-main">
 <div className="section-head"><div><span className="eyebrow dark">COMMERCE OPERATIONS</span><h1>Orders</h1><p className="muted">Search, filter and safely operate the live order queue.</p></div><Link className="button dark-button" href="/admin/orders/new">+ Manual Order</Link></div>
 <form className="admin-order-filters" method="get"><input className="input" name="q" defaultValue={q} placeholder="Search order, customer or phone"/><select className="input" name="status" defaultValue={status}><option value="">All statuses</option>{['CREATED','PAYMENT_PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','RETURN_REQUESTED','RETURNED','REFUNDED'].map(x=><option key={x}>{x}</option>)}</select><button className="button" type="submit">Search</button>{(q||status)&&<Link className="button secondary" href="/admin/orders">Clear</Link>}</form>
 <AdminBulkOrderActions/>
 <div className="table-wrap"><table className="table"><thead><tr><th><span className="sr-only">Select</span></th><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Fulfillment</th><th>Operations</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><input data-admin-order-select type="checkbox" value={o.id} aria-label={`Select ${o.orderNumber}`}/></td><td><Link href={`/admin/orders/${o.id}`}><strong>{o.orderNumber}</strong></Link><br/><small>{o.createdAt.toLocaleString('en-IN')}</small></td><td>{o.user?.name||'Guest'}<br/>{o.user?.phone}</td><td>{o.items.length}</td><td>{money(o.total)}</td><td>{o.payment?.status||'—'}</td><td>{o.fulfillmentStatus}<br/>{o.shipment?.trackingNumber||'No AWB'}</td><td><AdminOrderActions orderId={o.id} status={o.status} hasShipment={!!o.shipment} paymentStatus={o.payment?.status||''} total={o.total} shipment={o.shipment}/></td></tr>)}</tbody></table></div>{!rows.length&&<div className="empty">No matching orders.</div>}<p className="muted" style={{marginTop:10}}>Showing up to 100 orders. Bulk status changes are audited and pass through the central order-state event pipeline.</p>
 </section></div></div>}
