import Link from 'next/link';
import { getProductsForHomeSection } from '@/lib/storefront-data';
import HomeHeroCarousel from '@/components/HomeHeroCarousel';
import HomeImageCarousel from '@/components/HomeImageCarousel';
import HomeProductGrid from '@/components/HomeProductGrid';

type Section={id:string|number;key?:string;type?:string;title?:string;subtitle?:string;imageUrl?:string;mobileImageUrl?:string;ctaHref?:string;ctaLabel?:string;sortOrder?:number;content?:Record<string,any>;items?:any[];html?:string;query?:Record<string,any>};
const text=(v:unknown)=>String(v??'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g,' ').trim();
const type=(s:Section)=>String(s.type||s.key||'').toLowerCase();
const url=(v:unknown)=>{const x=String(v||'').trim();return !x?'/shop':x.startsWith('/')||x.startsWith('http://')||x.startsWith('https://')?x:`/${x}`};
const items=(s:Section)=>Array.isArray(s.items)?s.items:Array.isArray(s.content?.items)?s.content.items:[];
const image=(x:any)=>x?.image_url||x?.imageUrl||x?.image||x?.media?.url||'';
const title=(x:any)=>text(x?.title||x?.name||'');
const sub=(x:any)=>text(x?.subtitle||x?.description||'');
const cta=(x:any)=>({label:text(x?.cta_label||x?.ctaLabel||''),href:url(x?.cta_href||x?.ctaHref)});
function slides(s:Section){return items(s).map((x:any,i:number)=>({id:String(x?.id??`${s.id}-${i}`),title:title(x)||s.title,subtitle:sub(x)||text(s.subtitle),imageUrl:image(x)||s.imageUrl,mobileImageUrl:x?.mobile_image_url||x?.mobileImageUrl||s.mobileImageUrl||image(x)||s.imageUrl,ctaLabel:cta(x).label||text(s.ctaLabel),ctaHref:cta(x).href||url(s.ctaHref)}));}
async function Products({s}:{s:Section}){const n=Math.min(Math.max(Number(s.query?.limit||8),1),30);const p=await getProductsForHomeSection(type(s),n,s.query||{});if(!p.length)return null;return <section className={`home-section home-product-section ${type(s).includes('sale')?'home-flash-sale':''}`}><div className="home-section-head"><div><span className="home-kicker">{text(s.subtitle)}</span><h2>{text(s.title)}</h2></div>{s.ctaHref&&<Link className="home-view-all" href={url(s.ctaHref)}>{text(s.ctaLabel)||'View All'} →</Link>}</div><HomeProductGrid products={p} initialVisible={n} step={n}/></section>}
function Categories({s}:{s:Section}){const a=items(s);if(!a.length)return null;return <section className="home-section"><div className="home-section-head"><div><span className="home-kicker">{text(s.subtitle)}</span><h2>{text(s.title)}</h2></div>{s.ctaHref&&<Link className="home-view-all" href={url(s.ctaHref)}>{text(s.ctaLabel)||'View All'} →</Link>}</div><div className="category-grid category-grid-editorial">{a.map((x:any,i:number)=>{const q=cta(x);return <Link className="category-card" key={String(x?.id??`${s.id}-${i}`)} href={q.href}><div className="category-image" style={image(x)?{backgroundImage:`url(${image(x)})`}:undefined}/><div className="category-label"><strong>{title(x)}</strong><span>{q.label||'Shop Now'} →</span></div></Link>})}</div></section>}
function Offer({s}:{s:Section}){const a=items(s),x=a[0],q=cta(x||{});return <section className="home-section home-api-offer"><div className="home-api-offer-inner"><div className="home-api-offer-copy"><span className="home-kicker">{text(s.subtitle)}</span><h2>{text(s.title)}</h2>{a.map((v:any,i:number)=><p key={String(v?.id??i)}>{sub(v)}</p>)}{s.ctaHref||q.label?<Link className="button dark-button" href={s.ctaHref?url(s.ctaHref):q.href}>{text(s.ctaLabel)||q.label||'Shop Now'} →</Link>:null}</div>{x&&image(x)&&<div className="home-api-offer-image"><img src={image(x)} alt={title(x)||text(s.title)}/></div>}</div></section>}
function Banner({s}:{s:Section}){const a=items(s),x=a[0],im=s.imageUrl||image(x),mob=s.mobileImageUrl||x?.mobile_image_url||x?.mobileImageUrl||im;return <section className="home-section home-api-banner"><div className="home-api-banner-copy"><span className="home-kicker">{text(s.subtitle)}</span><h2>{text(s.title)}</h2>{s.ctaHref&&<Link className="button dark-button" href={url(s.ctaHref)}>{text(s.ctaLabel)||'Shop Now'} →</Link>}</div>{im&&<picture className="home-api-banner-media">{mob&&<source media="(max-width:760px)" srcSet={mob}/>}<img src={im} alt={text(s.title)} loading="lazy"/></picture>}</section>}
function TextSection({s}:{s:Section}){const body=text(s.html);if(!body&&!s.title&&!s.subtitle)return null;return <section className="home-section home-api-text">{s.subtitle&&<span className="home-kicker">{text(s.subtitle)}</span>}{s.title&&<h2>{text(s.title)}</h2>}{body&&<p>{body}</p>}{s.ctaHref&&<Link className="home-view-all" href={url(s.ctaHref)}>{text(s.ctaLabel)||'Explore'} →</Link>}</section>}
export async function renderHomeSections(sections:Section[]){const active=sections.filter(s=>s&&s.type&&s.id).sort((a,b)=>Number(a.sortOrder||0)-Number(b.sortOrder||0));const out:React.ReactNode[]=[];for(const s of active){const t=type(s);if(t==='hero_slider'||t==='hero'||t==='hero-slide'){const a=slides(s);if(a.length)out.push(<section className="home-section home-hero-multi" key={String(s.id)}><HomeHeroCarousel slides={a}/></section>);continue}if(t==='image-carousel'||t==='image-slide'||t==='carousel'){const a=slides(s);if(a.length)out.push(<section className="home-section home-image-highlight-section" key={String(s.id)}><HomeImageCarousel slides={a}/></section>);continue}if(['new_arrivals','new-arrivals','products-latest','latest','latest-collection','trending','best-sellers','products-best','products-sale','sale'].includes(t)){out.push(<Products s={s} key={String(s.id)}/>);continue}if(t==='category_grid'||t==='category-grid'){out.push(<Categories s={s} key={String(s.id)}/>);continue}if(t==='offer'||t==='promo'){out.push(<Offer s={s} key={String(s.id)}/>);continue}if(['banner','image-banner','collection-banner','feature'].includes(t)){out.push(<Banner s={s} key={String(s.id)}/>);continue}if(t==='text')out.push(<TextSection s={s} key={String(s.id)}/>)}return out}
