import Link from 'next/link';
import { getProductsForHomeSection } from '@/lib/storefront-data';
import HomeHeroCarousel from '@/components/HomeHeroCarousel';
import HomeImageCarousel from '@/components/HomeImageCarousel';
import HomeProductGrid from '@/components/HomeProductGrid';

type Section={id:string|number;key?:string;type?:string;title?:string|null;subtitle?:string|null;imageUrl?:string;mobileImageUrl?:string;ctaHref?:string;ctaLabel?:string;sortOrder?:number;sort_order?:number;isActive?:boolean;is_active?:boolean;content?:Record<string,any>;items?:any[];html?:string;query?:Record<string,any>};
const text=(v:unknown)=>String(v??'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g,' ').trim();
const type=(s:Section)=>String(s.type||s.key||'').toLowerCase().trim();
const href=(v:unknown)=>{const x=String(v??'').trim();return x&&(x.startsWith('/')||x.startsWith('http://')||x.startsWith('https://'))?x:x?`/${x}`:null};
const items=(s:Section)=>Array.isArray(s.items)?s.items:Array.isArray(s.content?.items)?s.content.items:[];
const query=(s:Section)=>s.query&&typeof s.query==='object'?s.query:s.content?.query&&typeof s.content.query==='object'?s.content.query:{};
const image=(x:any)=>x?.image_url||x?.imageUrl||x?.image||x?.media?.url||'';
const title=(x:any)=>text(x?.title||x?.name||'');
const sub=(x:any)=>text(x?.subtitle||x?.description||'');
const cta=(x:any)=>({label:text(x?.cta_label||x?.ctaLabel||''),href:href(x?.cta_href||x?.ctaHref)});
function slides(s:Section){return items(s).map((x:any,i:number)=>{const q=cta(x);return{id:String(x?.id??`${s.id}-${i}`),title:title(x)||text(s.title),subtitle:sub(x)||text(s.subtitle),imageUrl:image(x)||s.imageUrl,mobileImageUrl:x?.mobile_image_url||x?.mobileImageUrl||s.mobileImageUrl||image(x)||s.imageUrl,ctaLabel:q.label||text(s.ctaLabel),ctaHref:q.href||href(s.ctaHref)}}).filter((x:any)=>x.imageUrl);}
async function Products({s}:{s:Section}){const q=query(s);const n=Math.min(Math.max(Number(q.limit??8)||8,1),30);const t=type(s)==='new_arrivals'||type(s)==='new-arrivals'?'latest':type(s);const p=await getProductsForHomeSection(t,n,{sort:typeof q.sort==='string'?q.sort:undefined});if(!p.length)return null;const view=href(s.ctaHref);return <section className={`home-section home-product-section ${t.includes('sale')?'home-flash-sale':''}`}><div className="home-section-head"><div>{text(s.subtitle)&&<span className="home-kicker">{text(s.subtitle)}</span>}{text(s.title)&&<h2>{text(s.title)}</h2>}</div>{view&&<Link className="home-view-all" href={view}>{text(s.ctaLabel)}{text(s.ctaLabel)&&' →'}</Link>}</div><HomeProductGrid products={p} initialVisible={n} step={n}/></section>}
function Categories({s}:{s:Section}){const a=items(s).filter((x:any)=>title(x)||image(x));if(!a.length)return null;const view=href(s.ctaHref);return <section className="home-section"><div className="home-section-head"><div>{text(s.subtitle)&&<span className="home-kicker">{text(s.subtitle)}</span>}{text(s.title)&&<h2>{text(s.title)}</h2>}</div>{view&&<Link className="home-view-all" href={view}>{text(s.ctaLabel)}{text(s.ctaLabel)&&' →'}</Link>}</div><div className="category-grid category-grid-editorial">{a.map((x:any,i:number)=>{const q=cta(x);const cardHref=q.href;return cardHref?<Link className="category-card" key={String(x?.id??`${s.id}-${i}`)} href={cardHref}><div className="category-image" style={image(x)?{backgroundImage:`url(${image(x)})`}:undefined}/><div className="category-label"><strong>{title(x)}</strong>{q.label&&<span>{q.label} →</span>}</div></Link>:<div className="category-card" key={String(x?.id??`${s.id}-${i}`)}><div className="category-image" style={image(x)?{backgroundImage:`url(${image(x)})`}:undefined}/><div className="category-label"><strong>{title(x)}</strong></div></div>})}</div></section>}
function Offer({s}:{s:Section}){const a=items(s),x=a[0],q=cta(x||{});if(!x&&!text(s.title)&&!text(s.subtitle))return null;const offerHref=href(s.ctaHref)||q.href;const offerLabel=text(s.ctaLabel)||q.label;return <section className="home-section home-api-offer"><div className="home-api-offer-inner"><div className="home-api-offer-copy">{text(s.subtitle)&&<span className="home-kicker">{text(s.subtitle)}</span>}{text(s.title)&&<h2>{text(s.title)}</h2>}{a.map((v:any,i:number)=>sub(v)&&<p key={String(v?.id??i)}>{sub(v)}</p>)}{offerHref&&offerLabel&&<Link className="button dark-button" href={offerHref}>{offerLabel} →</Link>}</div>{x&&image(x)&&<div className="home-api-offer-image"><img src={image(x)} alt={title(x)||text(s.title)}/></div>}</div></section>}
function Banner({s}:{s:Section}){const a=items(s),x=a[0],im=s.imageUrl||image(x),mob=s.mobileImageUrl||x?.mobile_image_url||x?.mobileImageUrl||im;if(!text(s.title)&&!text(s.subtitle)&&!im)return null;const bannerHref=href(s.ctaHref);return <section className="home-section home-api-banner"><div className="home-api-banner-copy">{text(s.subtitle)&&<span className="home-kicker">{text(s.subtitle)}</span>}{text(s.title)&&<h2>{text(s.title)}</h2>}{bannerHref&&text(s.ctaLabel)&&<Link className="button dark-button" href={bannerHref}>{text(s.ctaLabel)} →</Link>}</div>{im&&<picture className="home-api-banner-media">{mob&&<source media="(max-width:760px)" srcSet={mob}/>}<img src={im} alt={text(s.title)} loading="lazy"/></picture>}</section>}
function TextSection({s}:{s:Section}){const body=text(s.html||s.content?.html);if(!body&&!text(s.title)&&!text(s.subtitle))return null;const textHref=href(s.ctaHref);return <section className="home-section home-api-text">{text(s.subtitle)&&<span className="home-kicker">{text(s.subtitle)}</span>}{text(s.title)&&<h2>{text(s.title)}</h2>}{body&&<p>{body}</p>}{textHref&&text(s.ctaLabel)&&<Link className="home-view-all" href={textHref}>{text(s.ctaLabel)} →</Link>}</section>}
export async function renderHomeSections(sections:Section[]){const active=sections.filter(s=>s&&s.id!=null&&s.type&&s.isActive!==false&&s.is_active!==false).sort((a,b)=>Number(a.sort_order??a.sortOrder??0)-Number(b.sort_order??b.sortOrder??0));const out:React.ReactNode[]=[];for(const s of active){const t=type(s);if(t==='hero_slider'||t==='hero'||t==='hero-slide'){const a=slides(s);if(a.length)out.push(<section className="home-section home-hero-multi" key={String(s.id)}><HomeHeroCarousel slides={a}/></section>);continue}if(t==='image-carousel'||t==='image-slide'||t==='carousel'){const a=slides(s);if(a.length)out.push(<section className="home-section home-image-highlight-section" key={String(s.id)}><HomeImageCarousel slides={a}/></section>);continue}if(['new_arrivals','new-arrivals','products-latest','latest','latest-collection','trending','best-sellers','products-best','products-sale','sale'].includes(t)){out.push(<Products s={s} key={String(s.id)}/>);continue}if(t==='category_grid'||t==='category-grid'){out.push(<Categories s={s} key={String(s.id)}/>);continue}if(t==='offer'||t==='promo'){out.push(<Offer s={s} key={String(s.id)}/>);continue}if(['banner','image-banner','collection-banner','feature'].includes(t)){out.push(<Banner s={s} key={String(s.id)}/>);continue}if(t==='text')out.push(<TextSection s={s} key={String(s.id)}/>)}return out}
