import Link from 'next/link';
import {redirect} from 'next/navigation';
import {db} from '@/lib/db';
import {getSession} from '@/lib/auth';
import s from './admin-modern.module.css';

const modules=[
 ['01','Product Experience','PDP gallery, variants, size guide, delivery and conversion tools','/admin/products','▦'],['02','Smart Cart','Cart drawer, quantity controls, shipping progress and upsells','/admin/orders','🛒'],['03','Cart Intelligence','Recently viewed, recommendations and recovery signals','/admin/marketing','✦'],['04','Reviews & Q&A','Ratings, verified reviews, moderation and customer feedback','/admin/reviews','★'],['05','Wishlist & Personalization','Wishlist, preferences and customer intent signals','/admin/customers','♡'],['06','Search & Discovery','Advanced search, filters, autocomplete and zero-result recovery','/search','⌕'],['07','Catalog Discovery','Categories, collections, product listing and merchandising','/admin/categories','◈'],['08','Recommendations','Similar products, frequently bought together and personalized picks','/admin/analytics','✦'],['09','Checkout & Payments','OTP gate, address, pincode, coupons, COD and Razorpay flow','/admin/orders','✓'],['10','Order Tracking','Order timeline, shipment status, tracking and post-purchase actions','/admin/orders','↗'],['11','SEO & Organic','Metadata, canonical URLs, structured data, sitemap and robots','/admin/seo','⌁'],['12','Performance','Image optimization, caching, responsive and Core Web Vitals foundations','/admin/seo','⚡'],['13','Notifications','Customer notifications, email and WhatsApp lifecycle delivery','/admin/whatsapp','◌'],['14','Automation Control','Triggers, conditions, actions, runs and campaign recipes','/admin/automations','⚙'],['15','Commerce Analytics','Revenue, orders, customer and operational performance','/admin/analytics','◒'],['16','Inventory Intelligence','Stock health, low-stock monitoring, warehouses and movements','/admin/inventory','▥'],['17','Fulfillment Control','Shipment events, carrier status and fulfillment state machine','/admin/orders','⇢'],['18','Returns & Refunds','Return requests, approvals, exchanges and refund operations','/admin/returns-refunds','↩'],['19','Financial Operations','Payments, Razorpay verification, refunds and reconciliation','/admin/analytics','₹'],['20','Admin Control Center','Orders, products, permissions, bulk actions and auditability','/admin/settings','⌘'],['21','Customer CRM','Customer 360, LTV, order history, notes and activity','/admin/customers','♙'],['22','Catalog Operations','Product creation, variants, pricing, WooCommerce import and bulk tools','/admin/products','▤'],['23','Merchandising & CMS','Category hierarchy, homepage studio, scheduling and live merchandising','/admin/cms','▣'],
] as const;
const nav=[['Overview','/admin','⌂'],['Orders','/admin/orders','▤'],['Products','/admin/products','▦'],['Inventory','/admin/inventory','▥'],['Customers','/admin/customers','♙'],['Marketing','/admin/marketing','◉'],['Automation','/admin/automations','⚙'],['Analytics','/admin/analytics','◒'],['Fulfillment','/admin/orders','⇢'],['Returns & Refunds','/admin/returns-refunds','↩'],['CMS Studio','/admin/cms','▣'],['Settings','/admin/settings','⚙']] as const;
function money(value:number){return `₹${Math.round(value).toLocaleString('en-IN')}`}
function initials(name:string){return name.split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()||'P'}
function statusLabel(value:string){return value.replaceAll('_',' ')}

export default async function Admin(){
 const session=await getSession();
 if(!session||!['ADMIN','STAFF'].includes(session.role)) redirect('/admin/login');
 const admin=await db.user.findUnique({where:{id:session.userId},select:{name:true,email:true,phone:true}});
 const [orders,customers,products,variants,coupons,categories,cms,shipments,payments,revenue,recentOrders,lowStock]=await Promise.all([
  db.order.count(),db.user.count({where:{role:'CUSTOMER'}}),db.product.count({where:{active:true}}),db.productVariant.count(),db.coupon.count({where:{active:true}}),db.category.count(),db.cmsSection.count({where:{active:true}}),db.shipment.count({where:{status:{in:['PICKED_UP','IN_TRANSIT','OUT_FOR_DELIVERY']}}}),db.payment.count({where:{status:'FAILED'}}),db.order.aggregate({where:{status:{in:['CONFIRMED','PROCESSING','SHIPPED','DELIVERED']}},_sum:{total:true}}),db.order.findMany({take:6,orderBy:{createdAt:'desc'},select:{orderNumber:true,total:true,status:true,createdAt:true,user:{select:{name:true,phone:true}}}}),db.productVariant.count({where:{stock:{lte:5}}}),
 ]);
 const name=admin?.name||'Admin';
 return <div className={s.shell}>
  <aside className={s.side}><Link href="/admin" className={s.brand}><span className={s.brandMark}>P</span><span className={s.brandText}><strong>PRIYASA</strong><small>COMMERCE OS</small></span></Link><div className={s.navTitle}>Command Center</div><nav className={s.nav}>{nav.map(([label,href,icon])=><Link key={label} href={href} className={label==='Overview'?s.active:''}><span className={s.navIcon}>{icon}</span>{label}</Link>)}</nav><div className={s.navTitle}>Commerce tools</div><nav className={s.nav}>{[['WooCommerce','/admin/products/woocommerce'],['Product Import','/admin/products/import'],['Coupons & Offers','/admin/coupons-offers'],['Meta Ads','/admin/meta-ads'],['WhatsApp','/admin/whatsapp'],['Reviews','/admin/reviews'],['SEO','/admin/seo'],['Audit Log','/admin/audit-log']].map(([label,href])=><Link key={label} href={href}><span className={s.navIcon}>•</span>{label}</Link>)}</nav></aside>
  <section className={s.main}><header className={s.top}><input className={s.search} placeholder="Search orders, products, customers, SKUs…" aria-label="Search admin"/><span className={s.topSpacer}/><Link className={s.topLink} href="/">View Store ↗</Link><Link className={s.topLink} href="/admin/settings">Settings</Link><span className={s.avatar}>{initials(name)}</span></header>
   <main className={s.content}><div className={s.head}><div><span className={s.kicker}>Priyasa Commerce OS</span><h1>Good morning, {name.split(' ')[0]}.</h1><p>One command center for the entire customer, catalog, order and growth lifecycle.</p></div><div className={s.headActions}><Link className={s.secondary} href="/admin/products/new">+ Product</Link><Link className={s.primary} href="/admin/orders/new">+ Manual Order</Link></div></div>
    <div className={s.stats}>{[['Revenue',money(revenue._sum.total||0),'Paid order value','₹'],['Orders',orders.toLocaleString('en-IN'),'All order records','▤'],['Customers',customers.toLocaleString('en-IN'),'Registered customers','♙'],['Catalog',products.toLocaleString('en-IN'),`${variants.toLocaleString('en-IN')} total SKUs`,'▦']].map(([label,value,meta,icon])=><div className={s.stat} key={label}><div className={s.statTop}><div><div className={s.statLabel}>{label}</div><div className={s.statValue}>{value}</div><div className={s.statMeta}>{meta}</div></div><span className={s.statIcon}>{icon}</span></div></div>)}</div>
    <section className={s.section}><div className={s.sectionHead}><div><h2>Everything implemented, visible and actionable</h2><span>23 commerce capabilities</span></div></div><div className={s.modules}>{modules.map(([no,title,desc,href,icon])=><Link className={s.module} href={href} key={no}><div className={s.moduleTop}><span className={s.moduleIcon}>{icon}</span><span className={s.moduleNo}>#{no}</span></div><div><strong>{title}</strong><p>{desc}</p></div><div className={s.moduleCta}>Open control →</div></Link>)}</div></section>
    <section className={s.section}><div className={s.grid2}><div className={s.panel}><div className={s.panelHead}><h3>Latest Orders</h3><Link href="/admin/orders">Open order center →</Link></div><table className={s.table}><thead><tr><th>Order</th><th>Customer</th><th>Value</th><th>Status</th><th>Date</th></tr></thead><tbody>{recentOrders.map(o=><tr key={o.orderNumber}><td>#{o.orderNumber}</td><td>{o.user?.name||o.user?.phone||'Guest'}</td><td>{money(o.total)}</td><td><span className={s.pill}>{statusLabel(o.status)}</span></td><td>{o.createdAt.toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</td></tr>)}{recentOrders.length===0&&<tr><td colSpan={5}>No orders yet.</td></tr>}</tbody></table></div>
    <div className={s.panel}><div className={s.panelHead}><h3>Operations Health</h3><Link href="/admin/analytics">View analytics →</Link></div><div className={s.health}><div className={s.healthRow}><i className={s.healthDot}/><div><strong>Inventory</strong><span>{lowStock} variants at or below 5 units</span></div></div><div className={s.healthRow}><i className={s.healthDot}/><div><strong>Fulfillment</strong><span>{shipments} shipments currently moving</span></div></div><div className={s.healthRow}><i className={s.healthDot}/><div><strong>Payments</strong><span>{payments} failed payment records</span></div></div><div className={s.healthRow}><i className={s.healthDot}/><div><strong>Merchandising</strong><span>{categories} categories · {cms} live CMS sections</span></div></div><div className={s.healthRow}><i className={s.healthDot}/><div><strong>Promotions</strong><span>{coupons} active coupons</span></div></div></div></div></div></section>
    <section className={s.section}><div className={s.panel}><div className={s.panelHead}><h3>Quick actions</h3><span>Common workflows</span></div><div className={s.quick}><Link href="/admin/inventory"><strong>Inventory</strong><span>Low stock & movements</span></Link><Link href="/admin/coupons-offers"><strong>Offers</strong><span>Coupons & promotions</span></Link><Link href="/admin/automations"><strong>Automation</strong><span>Triggers & campaigns</span></Link><Link href="/admin/returns-refunds"><strong>Returns</strong><span>Refund operations</span></Link><Link href="/admin/cms"><strong>Homepage Studio</strong><span>Merchandising & scheduling</span></Link><Link href="/admin/analytics"><strong>Analytics</strong><span>Revenue & customer insights</span></Link></div></div></section>
    <div className={s.footerNote}>Priyasa Commerce OS · The dashboard surfaces the live application routes and existing server-side controls.</div>
   </main></section>
 </div>;
}
