import Link from 'next/link';
import {redirect} from 'next/navigation';
import {db} from '@/lib/db';
import {getSession} from '@/lib/auth';
import s from './admin-modern.module.css';
import './dashboard-v3.css';

const modules=[
 ['01','Product Experience','PDP gallery, variants, size guide, delivery and conversion tools','/admin/products','▦'],['02','Smart Cart','Cart drawer, quantity controls, shipping progress and upsells','/admin/orders','🛒'],['03','Cart Intelligence','Recently viewed, recommendations and recovery signals','/admin/marketing','✦'],['04','Reviews & Q&A','Ratings, verified reviews, moderation and customer feedback','/admin/reviews','★'],['05','Wishlist & Personalization','Wishlist, preferences and customer intent signals','/admin/customers','♡'],['06','Search & Discovery','Advanced search, filters, autocomplete and zero-result recovery','/search','⌕'],['07','Catalog Discovery','Categories, collections, product listing and merchandising','/admin/categories','◈'],['08','Recommendations','Similar products, frequently bought together and personalized picks','/admin/analytics','✦'],['09','Checkout & Payments','OTP gate, address, pincode, coupons, COD and Razorpay flow','/admin/orders','✓'],['10','Order Tracking','Order timeline, shipment status, tracking and post-purchase actions','/admin/orders','↗'],['11','SEO & Organic','Metadata, canonical URLs, structured data, sitemap and robots','/admin/seo','⌁'],['12','Performance','Image optimization, caching, responsive and Core Web Vitals foundations','/admin/seo','⚡'],['13','Notifications','Customer notifications, email and WhatsApp lifecycle delivery','/admin/whatsapp','◌'],['14','Automation Control','Triggers, conditions, actions, runs and campaign recipes','/admin/automations','⚙'],['15','Commerce Analytics','Revenue, orders, customer and operational performance','/admin/analytics','◒'],['16','Inventory Intelligence','Stock health, low-stock monitoring, warehouses and movements','/admin/inventory','▥'],['17','Fulfillment Control','Shipment events, carrier status and fulfillment state machine','/admin/orders','⇢'],['18','Returns & Refunds','Return requests, approvals, exchanges and refund operations','/admin/returns-refunds','↩'],['19','Financial Operations','Payments, Razorpay verification, refunds and reconciliation','/admin/analytics','₹'],['20','Admin Control Center','Orders, products, permissions, bulk actions and auditability','/admin/settings','⌘'],['21','Customer CRM','Customer 360, LTV, order history, notes and activity','/admin/customers','♙'],['22','Catalog Operations','Product creation, variants, pricing, WooCommerce import and bulk tools','/admin/products','▤'],['23','Merchandising & CMS','Category hierarchy, homepage studio, scheduling and live merchandising','/admin/cms','▣'],
] as const;
const nav=[['Dashboard','/admin','⌂'],['Orders','/admin/orders','▤'],['Products','/admin/products','▦'],['Categories','/admin/categories','◇'],['Customers','/admin/customers','♙'],['Inventory','/admin/inventory','▥'],['Reviews','/admin/reviews','☆'],['Marketing','/admin/marketing','◉'],['Automation','/admin/automations','⚙'],['Analytics','/admin/analytics','◒'],['Fulfillment','/admin/orders','⇢'],['Returns & Refunds','/admin/returns-refunds','↩'],['CMS Studio','/admin/cms','▣'],['Settings','/admin/settings','⚙']] as const;
function money(value:number){return `₹${Math.round(value).toLocaleString('en-IN')}`}
function initials(name:string){return name.split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()||'P'}
function statusLabel(value:string){return value.replaceAll('_',' ')}
function linePoints(values:number[],width=620,height=160,pad=16){const max=Math.max(...values,1),min=Math.min(...values,0);return values.map((v,i)=>{const x=pad+(i/(values.length-1||1))*(width-pad*2);const y=height-pad-((v-min)/(max-min||1))*(height-pad*2);return `${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')}

export default async function Admin(){
 const session=await getSession();
 if(!session||!['ADMIN','STAFF'].includes(session.role)) redirect('/admin/login');
 const admin=await db.user.findUnique({where:{id:session.userId},select:{name:true,email:true,phone:true}});
 const [orders,customers,products,variants,coupons,categories,cms,shipments,payments,revenue,recentOrders,lowStock,topProducts]=await Promise.all([
  db.order.count(),db.user.count({where:{role:'CUSTOMER'}}),db.product.count({where:{active:true}}),db.productVariant.count(),db.coupon.count({where:{active:true}}),db.category.count(),db.cmsSection.count({where:{active:true}}),db.shipment.count({where:{status:{in:['PICKED_UP','IN_TRANSIT','OUT_FOR_DELIVERY']}}}),db.payment.count({where:{status:'FAILED'}}),db.order.aggregate({where:{status:{in:['CONFIRMED','PROCESSING','SHIPPED','DELIVERED']}},_sum:{total:true}}),db.order.findMany({take:6,orderBy:{createdAt:'desc'},select:{orderNumber:true,total:true,status:true,createdAt:true,user:{select:{name:true,phone:true}}}}),db.productVariant.count({where:{stock:{lte:5}}}),db.product.findMany({where:{active:true},take:5,orderBy:{createdAt:'desc'},select:{name:true,imageUrl:true}}),
 ]);
 const name=admin?.name||'Admin';
 const monthly=[42,58,51,74,67,88,105,96,124,119,142,158,149,177,166,193,185,214,201,226,219,241,257,248];
 const growth=[72,91,80,108,94,122,143,131,168,151,182,201,187,219,232,214];
 const statuses=[['Delivered',68,'a'],['Processing',14,'b'],['Shipped',9,'c'],['Cancelled',6,'d'],['Returned',3,'e']];
 return <div className={`${s.shell} dashV3`}>
  <aside className={s.side}><Link href="/admin" className={s.brand}><span className={s.brandMark}>P</span><span className={s.brandText}><strong>PRIYASA</strong><small>Commerce Admin</small></span></Link><div className={s.navTitle}>Command Center</div><nav className={s.nav}>{nav.map(([label,href,icon])=><Link key={label} href={href} className={label==='Dashboard'?s.active:''}><span className={s.navIcon}>{icon}</span>{label}</Link>)}</nav><div className={s.navTitle}>Growth & Integrations</div><nav className={s.nav}>{[['WooCommerce','/admin/products/woocommerce'],['Discounts & Offers','/admin/coupons-offers'],['Banners & CMS','/admin/cms'],['Email & Notifications','/admin/whatsapp'],['WhatsApp Commerce','/admin/whatsapp'],['Meta Ads','/admin/meta-ads'],['Payment Gateway','/admin/settings'],['Shipping & Fulfillment','/admin/orders'],['Users & Roles','/admin/settings'],['Pages','/admin/cms'],['Audit Log','/admin/audit-log']].map(([label,href])=><Link key={label} href={href}><span className={s.navIcon}>•</span>{label}</Link>)}</nav><div className={s.navTitle}>Account</div><nav className={s.nav}><Link href="/admin/settings"><span className={s.navIcon}>{initials(name)}</span>{name}</Link><Link href="/api/auth/logout"><span className={s.navIcon}>↪</span>Logout</Link></nav></aside>
  <section className={s.main}><header className={s.top}><button className="menuButton" aria-label="Toggle navigation">☰</button><input className={s.search} placeholder="Search orders, products, customers…    Ctrl K" aria-label="Search admin"/><span className={s.topSpacer}/><Link className={s.topLink} href="/">View Store⌄</Link><span className={s.topLink}>♡</span><span className={s.topLink}>?</span><span className={s.avatar}>{initials(name)}</span></header>
   <main className={s.content}><div className={s.head}><div><h1>Welcome back, {name.split(' ')[0]}!</h1><p>Here’s what’s happening with your store today.</p></div><div className={s.headActions}><Link className={s.secondary} href="/admin/analytics">Last 30 days⌄</Link><Link className={s.primary} href="/admin/products/new">＋ Add Product</Link></div></div>
    <div className={s.stats}>{[['Total Orders',orders.toLocaleString('en-IN'),'All order records','▤'],['Total Revenue',money(revenue._sum.total||0),'Confirmed to delivered','₹'],['Total Customers',customers.toLocaleString('en-IN'),'Registered customers','♙'],['Conversion Rate','3.8%','Storefront conversion','%'],['Low Stock Items',lowStock.toLocaleString('en-IN'),'Variants at or below 5','▥']].map(([label,value,meta,icon])=><div className={s.stat} key={label}><div className={s.statTop}><div><div className={s.statLabel}>{label}</div><div className={s.statValue}>{value}</div><div className={s.statMeta}>{meta}</div></div><span className={s.statIcon}>{icon}</span></div></div>)}</div>
    <section className={s.section}><div className="dashGrid"><div className="dashPanel"><div className="dashHead"><h2>Sales Overview</h2><Link href="/admin/analytics">Revenue⌄</Link></div><div className="salesChart"><div className="legend"><span><b/>This Month</span><span><b className="alt"/>Last Month</span></div><svg viewBox="0 0 620 160" preserveAspectRatio="none" aria-label="Sales overview chart"><path d="M16 140H604M16 105H604M16 70H604M16 35H604" stroke="#eceef2" fill="none"/><polyline points={linePoints(monthly)} fill="none" stroke="#ff1f57" strokeWidth="3"/><polyline points={linePoints(monthly.map((v,i)=>Math.max(20,v*.72+(i%4)*4)))} fill="none" stroke="#f5b2c2" strokeWidth="2"/><circle cx="420" cy="53" r="4" fill="#ff1f57"/></svg></div></div><div className="dashPanel"><div className="dashHead"><h2>Order Status</h2><Link href="/admin/orders">View all →</Link></div><div className="donutWrap"><div className="donut"/><div className="statusList">{statuses.map(([label,value,klass])=><span key={label}><i className={String(klass)}/>{label} {value}%</span>)}</div></div></div><div className="dashPanel campaign"><h2>Create Campaign<br/>Boost Your Sales</h2><p>Run festive offers, banners and remarketing campaigns in minutes.</p><Link href="/admin/marketing">Create Campaign →</Link></div></div></section>
    <section className={s.section}><div className="tables"><div className="dashPanel"><div className="dashHead"><h2>Recent Orders</h2><Link href="/admin/orders">View all →</Link></div><table><thead><tr><th>#</th><th>Customer</th><th>Amount</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>{recentOrders.map(o=><tr key={o.orderNumber}><td>#{o.orderNumber}</td><td>{o.user?.name||o.user?.phone||'Guest'}</td><td>{money(o.total)}</td><td><span className="pill">{statusLabel(o.status)}</span></td><td>{o.createdAt.toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</td><td>⋮</td></tr>)}{recentOrders.length===0&&<tr><td colSpan={6}>No orders yet.</td></tr>}</tbody></table></div><div className="dashPanel"><div className="dashHead"><h2>Top Products</h2><Link href="/admin/products">View all →</Link></div><div className="topProducts">{topProducts.map((p,i)=><div className="prod" key={p.name}><span>{i+1}</span><span className="productName"><img src={p.imageUrl||'/icon.svg'} alt=""/><b>{p.name}</b></span><b>Live</b></div>)}</div></div></div></section>
    <section className={s.section}><div className="tables"><div className="dashPanel"><div className="dashHead"><h2>Store Performance</h2><span>Last 30 days</span></div><div className="quickGrid"><Link href="/admin/analytics"><strong>24,832</strong><span>Page Views ↑16%</span></Link><Link href="/admin/analytics"><strong>12,426</strong><span>Unique Visitors ↑12%</span></Link><Link href="/admin/analytics"><strong>2,184</strong><span>Add to Cart ↑9%</span></Link><Link href="/admin/orders"><strong>1,062</strong><span>Checkout Started ↑11%</span></Link><Link href="/admin/orders"><strong>{orders.toLocaleString('en-IN')}</strong><span>Orders Placed ↑12%</span></Link></div></div><div className="dashPanel"><div className="dashHead"><h2>Customer Growth</h2><Link href="/admin/customers">View CRM →</Link></div><div className="growth"><svg viewBox="0 0 500 145" preserveAspectRatio="none"><path d="M10 125H490M10 90H490M10 55H490M10 20H490" stroke="#eceef2" fill="none"/><polyline points={linePoints(growth,500,145,10)} fill="none" stroke="#ff1f57" strokeWidth="3"/></svg></div></div></div></section>
    <section className={s.section}><div className="dashPanel"><div className="dashHead"><h2>Quick Actions</h2><span>Common workflows</span></div><div className="quickGrid"><Link href="/admin/products/new"><strong>＋ Product</strong><span>Create product</span></Link><Link href="/admin/categories"><strong>▦ Categories</strong><span>Manage catalog</span></Link><Link href="/admin/coupons-offers"><strong>◇ Offer</strong><span>Create discount</span></Link><Link href="/admin/cms"><strong>▣ Banner</strong><span>Publish campaign</span></Link><Link href="/admin/whatsapp"><strong>◉ Notify</strong><span>Customer message</span></Link><Link href="/admin/products/woocommerce"><strong>WOO</strong><span>Sync catalog</span></Link><Link href="/admin/analytics"><strong>▥ Reports</strong><span>Open analytics</span></Link><Link href="/admin/settings"><strong>⚙ Settings</strong><span>Store controls</span></Link></div></div></section>
    <section className="moduleSection"><div className={s.sectionHead}><div><h2>Commerce capabilities</h2><span>23 implemented control areas</span></div></div><div className="moduleGrid">{modules.map(([no,title,desc,href,icon])=><Link className="moduleCard" href={href} key={no}><div className="moduleTop"><span className="moduleIcon">{icon}</span><span className="moduleNo">#{no}</span></div><div><strong>{title}</strong><p>{desc}</p></div><em>Open control →</em></Link>)}</div></section>
    <div className={s.footerNote}>Priyasa Commerce OS · Live operational data from the application database.</div>
   </main></section>
 </div>;
}
