'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Row = { id: string; sku: string; size: string; color: string; price: number | null; stock: number; reserved: number; product: { id: string; name: string; category?: { name: string } | null; image?: string } };

export default function AdminBulkVariantsV2() {
  const [rows, setRows] = useState<Row[]>([]); const [selected, setSelected] = useState<string[]>([]); const [q, setQ] = useState(''); const [priceMode, setPriceMode] = useState('keep'); const [priceValue, setPriceValue] = useState(''); const [stockMode, setStockMode] = useState('keep'); const [stockValue, setStockValue] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState<string | null>(null); const [editPrice, setEditPrice] = useState(''); const [editStock, setEditStock] = useState('');

  async function load() { const r = await fetch('/api/admin/products', { cache: 'no-store' }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Unable to load variants'); setRows((d.data || []).flatMap((p: any) => (p.variants || []).map((v: any) => ({ ...v, product: { id: p.id, name: p.name, category: p.category, image: p.images?.[0]?.url } })))); }
  useEffect(() => { void load().catch((e) => setMessage(e.message)); }, []);
  const filtered = useMemo(() => { const s = q.trim().toLowerCase(); return !s ? rows : rows.filter((r) => [r.sku, r.size, r.color, r.product.name, r.product.category?.name || ''].join(' ').toLowerCase().includes(s)); }, [rows, q]);
  const allVisible = filtered.length > 0 && filtered.every((r) => selected.includes(r.id));

  async function applyBulk() { if (!selected.length) return setMessage('Select at least one variant.'); setBusy(true); setMessage('Updating variants…'); try { const r = await fetch('/api/admin/variants/bulk', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ variantIds: selected, priceMode, priceValue: priceMode === 'keep' ? undefined : Number(priceValue), stockMode, stockValue: stockMode === 'keep' ? undefined : Number(stockValue) }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Bulk update failed'); setMessage(`${d.updated || 0} variants updated successfully.`); setSelected([]); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Bulk update failed'); } finally { setBusy(false); } }
  async function saveSingle(id: string) { setBusy(true); try { const r = await fetch(`/api/admin/variants/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ price: editPrice === '' ? undefined : Number(editPrice), stock: editStock === '' ? undefined : Number(editStock) }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Update failed'); setEditing(null); setMessage('Variant updated.'); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Update failed'); } finally { setBusy(false); } }

  return <div className="variantOps"><div className="variantOpsHead"><div><span>CATALOG OPERATIONS · VARIANT LEVEL</span><h1>Price & Stock Control</h1><p>Update one SKU instantly or select hundreds of variants for a controlled bulk price and inventory operation.</p></div><div><Link href="/admin/products" className="variantLight">Products</Link><Link href="/admin/products/new" className="variantPrimary">＋ Add product</Link></div></div>
    {message && <div className="variantNotice">{message}</div>}
    <div className="variantStats"><div><small>Visible variants</small><strong>{filtered.length}</strong></div><div><small>Selected</small><strong>{selected.length}</strong></div><div><small>Low stock</small><strong>{filtered.filter((r) => Math.max(0, r.stock - r.reserved) <= 5).length}</strong></div><div><small>Reserved</small><strong>{filtered.reduce((n, r) => n + r.reserved, 0)}</strong></div></div>
    <section className="variantToolbar"><div className="variantSearch"><span>⌕</span><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search SKU, product, size or colour…"/></div><button className="variantLight" onClick={() => setSelected(allVisible ? [] : filtered.map((r) => r.id))}>{allVisible ? 'Clear visible' : 'Select visible'}</button><button className="variantLight" onClick={() => void load()}>↻ Refresh</button></section>
    <section className="variantBulk"><div><span>BULK OPERATION</span><h2>Apply to {selected.length || 'selected'} variants</h2></div><div className="variantControls"><label>Price<select value={priceMode} onChange={(e) => setPriceMode(e.target.value)}><option value="keep">Keep price</option><option value="set">Set exact</option><option value="increase-percent">Increase %</option><option value="decrease-percent">Decrease %</option></select></label><label>Value<input type="number" min="0" value={priceValue} onChange={(e) => setPriceValue(e.target.value)} disabled={priceMode === 'keep'} placeholder="₹ / %"/></label><label>Stock<select value={stockMode} onChange={(e) => setStockMode(e.target.value)}><option value="keep">Keep stock</option><option value="set">Set exact</option><option value="increase">Add units</option><option value="decrease">Reduce units</option></select></label><label>Units<input type="number" min="0" value={stockValue} onChange={(e) => setStockValue(e.target.value)} disabled={stockMode === 'keep'} placeholder="Units"/></label><button className="variantPrimary" disabled={busy || !selected.length} onClick={() => void applyBulk()}>{busy ? 'Updating…' : 'Apply changes'}</button></div><small>Stock reductions are protected: available stock cannot be reduced below currently reserved units. Every change is audited.</small></section>
    <section className="variantTable"><table><thead><tr><th><input type="checkbox" checked={allVisible} onChange={() => setSelected(allVisible ? [] : filtered.map((r) => r.id))}/></th><th>Product</th><th>SKU</th><th>Variant</th><th>Price</th><th>Stock</th><th>Reserved</th><th>Available</th><th>Quick edit</th></tr></thead><tbody>{filtered.map((row) => { const available = Math.max(0, row.stock - row.reserved); return <tr key={row.id}><td><input type="checkbox" checked={selected.includes(row.id)} onChange={() => setSelected((s) => s.includes(row.id) ? s.filter((x) => x !== row.id) : [...s, row.id])}/></td><td><div className="variantProduct"><img src={row.product.image || '/images/product-placeholder.svg'} alt=""/><span><strong>{row.product.name}</strong><small>{row.product.category?.name || 'Uncategorised'}</small></span></div></td><td>{row.sku}</td><td>{row.size} · {row.color}</td><td>{editing === row.id ? <input className="inlineInput" type="number" value={editPrice} onChange={(e) => setEditPrice(e.target.value)}/> : `₹${(row.price ?? 0).toLocaleString('en-IN')}`}</td><td>{editing === row.id ? <input className="inlineInput" type="number" min="0" value={editStock} onChange={(e) => setEditStock(e.target.value)}/> : row.stock}</td><td>{row.reserved}</td><td><b className={available <= 5 ? 'low' : ''}>{available}</b></td><td>{editing === row.id ? <span className="inlineActions"><button onClick={() => void saveSingle(row.id)}>Save</button><button onClick={() => setEditing(null)}>Cancel</button></span> : <button onClick={() => { setEditing(row.id); setEditPrice(String(row.price ?? '')); setEditStock(String(row.stock)); }}>Edit</button>}</td></tr>; })}</tbody></table>{!filtered.length && <div className="variantEmpty">No variants match your search.</div>}</section>
  </div>;
}
