'use client';
import {useState} from 'react';
export default function AdminProductBulkControls({products}:{products:{id:string;name:string;active:boolean;mrp:number;salePrice:number}[]}){
 const [selected,setSelected]=useState<string[]>([]);const [action,setAction]=useState('ACTIVATE');const [value,setValue]=useState('');const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');
 const all=products.length>0&&selected.length===products.length;
 function toggle(id:string){setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}
 async function apply(){if(!selected.length)return;setBusy(true);setMsg('');try{const body:any={productIds:selected,action};if(action==='SET_PRICE'||action==='SET_DISCOUNT')body.value=Number(value);const r=await fetch('/api/admin/products/bulk',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to update');setMsg(`${d.updated} product(s) updated`);location.reload()}catch(e){setMsg(e instanceof Error?e.message:'Unable to update')}finally{setBusy(false)}}
 return <div className="admin-card" style={{marginBottom:18}}><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><strong>Bulk catalog controls</strong><button type="button" className="button" onClick={()=>setSelected(all?[]:products.map(p=>p.id))}>{all?'Clear all':'Select all'}</button><span className="muted">{selected.length} selected</span>{selected.length>0&&<><select className="input" value={action} onChange={e=>setAction(e.target.value)}><option value="ACTIVATE">Publish</option><option value="DEACTIVATE">Unpublish</option><option value="SET_PRICE">Set sale price</option><option value="SET_DISCOUNT">Set discount %</option></select>{(action==='SET_PRICE'||action==='SET_DISCOUNT')&&<input className="input" style={{maxWidth:150}} type="number" min="0" value={value} onChange={e=>setValue(e.target.value)} placeholder={action==='SET_PRICE'?'Price':'Discount %'}/>}<button type="button" className="button dark-button" disabled={busy} onClick={apply}>{busy?'Updating…':'Apply'}</button></>}{msg&&<small className="muted">{msg}</small>}</div><div className="table-wrap" style={{marginTop:14}}><table className="table"><thead><tr><th></th><th>Product</th><th>Sale</th><th>MRP</th><th>Status</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)} aria-label={`Select ${p.name}`}/></td><td>{p.name}</td><td>₹{p.salePrice.toLocaleString('en-IN')}</td><td>₹{p.mrp.toLocaleString('en-IN')}</td><td>{p.active?'Live':'Draft'}</td></tr>)}</tbody></table></div></div>
}
