'use client';
import Link from 'next/link';import {useEffect,useMemo,useState} from 'react';import type {Product} from '@/lib/catalog';import {BagIcon,SearchIcon} from '@/components/StorefrontIcons';import {ProductCard} from '@/components/ProductCard';
const TRENDING=['Kurtis','Anarkali','Kurta Set','Cotton Kurti','Festive Wear'];const KEY='priyasa_recent_searches';const PAGE_SIZE=24;
type F={category:string;size:string;color:string;min:string;max:string;sort:string};const EMPTY:F={category:'',size:'',color:'',min:'',max:'',sort:'relevance'};
export default function AdvancedStorefrontSearch({initialQuery='',initialCategory=''}:{initialQuery?:string;initialCategory?:string}){const[q,setQ]=useState(initialQuery),[items,setItems]=useState<Product[]>([]),[cats,setCats]=useState<any[]>([]),[f,setF]=useState<F>({...EMPTY,category:initialCategory}),[recent,setRecent]=useState<string[]>([]),[focus,setFocus]=useState(false),[open,setOpen]=useState(false),[visible,setVisible]=useState(PAGE_SIZE),[loading,setLoading]=useState(true),[error,setError]=useState(false);
useEffect(()=>{try{const raw=localStorage.getItem(KEY);const parsed=raw?JSON.parse(raw):[];setRecent(Array.isArray(parsed)?parsed.filter((x):x is string=>typeof x==='string').slice(0,6):[])}catch{setRecent([])}},[]);
const save=(v:string)=>{const value=v.trim();if(!value)return;setRecent(a=>{const n=[value,...a.filter(x=>x.toLowerCase()!==value.toLowerCase())].slice(0,6);try{localStorage.setItem(KEY,JSON.stringify(n))}catch{}return n})};
useEffect(()=>{let dead=false;const t=setTimeout(async()=>{setLoading(true);setError(false);try{const p=new URLSearchParams({q,limit:'100'});Object.entries(f).forEach(([k,v])=>v&&p.set(k,v));const r=await fetch('/api/storefront/search-advanced?'+p.toString(),{cache:'no-store'});if(!r.ok)throw new Error('search_failed');const d=await r.json();if(!dead){setItems(Array.isArray(d.data?.products)?d.data.products:[]);setCats(Array.isArray(d.data?.categories)?d.data.categories:[]);setVisible(PAGE_SIZE)}}catch{if(!dead){setItems([]);setCats([]);setError(true)}}finally{if(!dead)setLoading(false)}},160);return()=>{dead=true;clearTimeout(t)}},[q,f]);
const sizes=useMemo(()=>Array.from(new Set(items.flatMap(p=>Array.isArray(p.sizes)?p.sizes:[]))).filter(Boolean).sort(),[items]),colors=useMemo(()=>Array.from(new Set(items.flatMap(p=>Array.isArray(p.colors)?p.colors:[]))).filter(Boolean).sort(),[items]),suggestions=items.slice(0,5),active=Object.entries(f).filter(([k,v])=>k!=='sort'&&Boolean(v)).length,shown=items.slice(0,visible);
const choose=(v:string)=>{setQ(v);save(v);setFocus(false)};const set=(k:keyof F,v:string)=>setF(x=>({...x,[k]:v}));const clear=()=>setF({...EMPTY,category:initialCategory});
return <div className="search-experience"><div className="search-mobile-head"><Link href="/" className="back" aria-label="Back">‹</Link><button type="button" className="mobile-search-box" onClick={()=>document.getElementById('priyasa-search-input')?.focus()}><SearchIcon/><span>{q||'Search products, styles & categories'}</span></button><Link href="/cart" className="bag-link" aria-label="Bag"><BagIcon/></Link></div>
<div className="search-hero"><span className="eyebrow dark">FIND YOUR PRIYASA EDIT</span><h1>{q?`Results for “${q}”`:'What are you looking for?'}</h1><div className="search-input-wrap"><input id="priyasa-search-input" autoFocus value={q} onChange={e=>setQ(e.target.value)} onFocus={()=>setFocus(true)} onBlur={()=>setTimeout(()=>setFocus(false),150)} placeholder="Search kurtis, dresses, ethnic wear..." aria-label="Search products" autoComplete="off"/><button onMouseDown={e=>e.preventDefault()} onClick={()=>setQ('')} aria-label="Clear search">{q?'×':''}</button>{focus&&!q&&<div className="search-suggestion-panel"><b>Trending searches</b>{TRENDING.map(x=><button key={x} onMouseDown={()=>choose(x)}>⌕ {x}</button>)}{recent.length>0&&<><b>Recent searches</b>{recent.map(x=><button key={x} onMouseDown={()=>choose(x)}>↻ {x}</button>)}</>}</div>}{focus&&q&&!loading&&suggestions.length>0&&<div className="search-suggestion-panel live"><b>Suggestions</b>{suggestions.map(p=><Link key={p.id} href={`/product/${p.slug}`} onMouseDown={()=>save(q)}><img src={p.image||'/images/product-placeholder.svg'} alt=""/><span>{p.name}<small>{p.category}</small></span></Link>)}</div>}</div><div className="search-chips"><span>Try</span>{TRENDING.map(x=><button key={x} onClick={()=>choose(x)}>{x}</button>)}</div></div>
<div className="search-toolbar"><strong>{loading?'Finding styles…':error?'Search unavailable':`${items.length} styles`}{q&&!loading&&!error&&<span> for “{q}”</span>}</strong><div className="search-toolbar-actions"><button className="filter-toggle" onClick={()=>setOpen(x=>!x)} aria-expanded={open}>Filters {active>0&&<b>{active}</b>}</button><label className="sort-control">Sort <select value={f.sort} onChange={e=>set('sort',e.target.value)}><option value="relevance">Relevance</option><option value="newest">Newest</option><option value="price_asc">Price: Low to High</option><option value="price_desc">Price: High to Low</option><option value="discount">Discount</option><option value="name">Name</option></select></label></div></div>
{open&&<section className="search-filter-panel" aria-label="Product filters">{[['category','Category',cats.map(c=>[c.slug,c.name])],['size','Size',sizes.map(x=>[x,x])],['color','Color',colors.map(x=>[x,x])]].map(([k,label,opts]:any)=><div key={k}><b>{label}</b><select value={(f as any)[k]} onChange={e=>set(k,e.target.value)}><option value="">All {String(label).toLowerCase()}</option>{opts.map((x:string[])=> <option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div>)}<div><b>Price range</b><div className="price-inputs"><input inputMode="numeric" placeholder="Min ₹" value={f.min} onChange={e=>set('min',e.target.value.replace(/\D/g,''))}/><input inputMode="numeric" placeholder="Max ₹" value={f.max} onChange={e=>set('max',e.target.value.replace(/\D/g,''))}/></div></div><button className="clear-filter" onClick={clear}>Clear all</button><button className="button filter-done" onClick={()=>setOpen(false)}>View {items.length} styles</button></section>}
<section className="section search-results-section">{loading?<div className="product-grid product-grid-editorial" aria-label="Loading products">{Array.from({length:8},(_,i)=><div className="product-skeleton" key={i}><div/><span/><small/></div>)}</div>:error?<div className="search-empty"><h3>We couldn’t load the collection.</h3><p>Please retry in a moment.</p><button className="button" onClick={()=>setQ(v=>v+' ')}>Retry</button></div>:shown.length?<><div className="product-grid product-grid-editorial">{shown.map(p=><ProductCard key={p.id} product={p}/>)}</div>{visible<items.length&&<div className="search-load-more"><button className="button" onClick={()=>setVisible(v=>v+PAGE_SIZE)}>Load more</button><span>Showing {shown.length} of {items.length}</span></div>}</>:<div className="search-empty"><h3>No exact match yet.</h3><p>Try a simpler spelling, category, color or size.</p><div className="zero-result-suggestions">{TRENDING.map(x=><button key={x} onClick={()=>choose(x)}>{x}</button>)}</div><button className="button" onClick={()=>{setQ('');clear()}}>Explore latest launches</button></div>}</section></div>}
