'use client';
import {useEffect,useState} from 'react';

type Props={weightGrams?:number;cod?:boolean;compact?:boolean;onAddress?: (address:{pincode:string;city:string;state:string;area?:string})=>void};
type Result={serviceable:boolean;etaText?:string;shippingCharge?:number;codAvailable?:boolean;courier?:string;message:string};
export function DeliveryPincode({weightGrams=500,cod=false,compact=false,onAddress}:Props){
 const [pincode,setPincode]=useState('');const [result,setResult]=useState<Result|null>(null);const [loading,setLoading]=useState(false);const [lookup,setLookup]=useState(false);const [error,setError]=useState('');const [locationLoading,setLocationLoading]=useState(false);
 const lookupPin=async(pin:string)=>{if(pin.length!==6)return;setLookup(true);try{const r=await fetch(`/api/location/pincode?pincode=${pin}`,{cache:'no-store'});const d=await r.json();if(r.ok&&d.found){onAddress?.({pincode:pin,city:d.city,state:d.state,area:d.area});return true}if(!r.ok)setError(d.error||d.message||'Pincode not found.');}catch{setError('Unable to fetch address for this pincode.')}finally{setLookup(false)}return false};
 const check=async(value=pincode)=>{const pin=value.replace(/\D/g,'').slice(0,6);setPincode(pin);setError('');setResult(null);if(pin.length!==6)return;await lookupPin(pin);setLoading(true);try{const r=await fetch(`/api/shipping/serviceability?pincode=${pin}&weightGrams=${weightGrams}&cod=${cod?'1':'0'}`,{cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'Unable to check delivery');setResult(data)}catch(e){setError(e instanceof Error?e.message:'Unable to check delivery')}finally{setLoading(false)}};
 const useLocation=()=>{if(!navigator.geolocation){setError('Location is not supported on this device.');return}setLocationLoading(true);setError('');navigator.geolocation.getCurrentPosition(async pos=>{try{const r=await fetch(`/api/location/reverse?lat=${pos.coords.latitude}&lon=${pos.coords.longitude}`,{cache:'no-store'});const d=await r.json();if(!r.ok||!d.pincode)throw new Error(d.error||'Could not detect a delivery pincode');setPincode(d.pincode);onAddress?.({pincode:d.pincode,city:d.city||'',state:d.state||'',area:d.area||''});await check(d.pincode)}catch(e){setError(e instanceof Error?e.message:'Unable to detect your address.')}finally{setLocationLoading(false)}},()=>{setLocationLoading(false);setError('Location permission was not granted.')},{enableHighAccuracy:false,timeout:10000,maximumAge:300000})};
 useEffect(()=>{const saved=localStorage.getItem('priyasa_delivery_pincode');if(saved&&/^\d{6}$/.test(saved))setPincode(saved)},[]);
 useEffect(()=>{if(result?.serviceable&&pincode.length===6)localStorage.setItem('priyasa_delivery_pincode',pincode)},[result,pincode]);
 return <div className={`delivery-check premium-delivery-check ${compact?'delivery-check-compact':''}`}><div className="delivery-title"><span className="delivery-icon">⌖</span><div><strong>Check delivery to your location</strong><small>Enter pincode or use your current location</small></div></div><div className="delivery-input-row"><input inputMode="numeric" maxLength={6} value={pincode} onChange={e=>{const v=e.target.value.replace(/\D/g,'').slice(0,6);setPincode(v);if(v.length===6)check(v)}} placeholder="6-digit pincode" aria-label="Delivery pincode"/><button type="button" onClick={()=>check()} disabled={loading||lookup||pincode.length!==6}>{loading||lookup?'Checking…':'Check'}</button><button type="button" className="location-button" onClick={useLocation} disabled={locationLoading}>{locationLoading?'Detecting…':'Use my location'}</button></div>{result&&<div className={`delivery-result ${result.serviceable?'success':'unavailable'}`}><strong>{result.serviceable?'✓ Delivery available':'× Delivery unavailable'}</strong><span>{result.serviceable?(result.etaText||'Delivery available to this pincode.'):'We currently cannot deliver to this pincode.'}</span>{result.serviceable&&result.codAvailable&&<span>✓ Cash on Delivery available</span>}</div>}{error&&<div className="delivery-error">{error}</div>}</div>;
}
