import Link from 'next/link';
import HomeHeroCarousel from '@/components/HomeHeroCarousel';
import HomeImageCarousel from '@/components/HomeImageCarousel';
import HomeProductGrid from '@/components/HomeProductGrid';
import {getCachedStorefrontProducts} from '@/lib/storefront-cache';
import {getStorefrontCategories,getProductsForHomeSection} from '@/lib/storefront-data';
import type {HomeCmsSection,StorefrontCategory} from '@/lib/storefront-data';

const clean=(v:any)=>String(v??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const typeOf=(s:any)=>String(s?.type||'').toLowerCase();
const img=(s:any)=>s?.imageUrl||s?.image_url||'';
const href=(s:any)=>s?.ctaHref||s?.cta_href||'/shop';
const label=(s:any)=>s?.ctaLabel||s?.cta_label||'Shop Now';
const itemsOf=(s:any)=>Array.isArray(s?.content?.items)?s.content.items:[];
const sortOf=(s:any)=>Number(s?.sortOrder??s?.sort_order??0);

function Heading({s}:{s:HomeCmsSection}){return <div className="home-section-head"><div>{s.subtitle&&<span className="home-kicker">{clean(s.subtitle)}</span>}<h2>{clean(s.title||'Priyasa')}</h2></div>{(s.ctaHref||s.cta_href)&&<Link className="home-view-all" href={href(s)}>{label(s)} →</Link>}</div>}
function Cards({items}:{items:any[]}){if(!items.length)return null;return <div className="home-cms-card-grid">{items.map((x:any,i:number)=><Link href={x.cta_href||x.ctaHref||x.href||'/shop'} className="home-cms-card" key={x.id||i}>{(x.image_url||x.imageUrl)&&<img src={x.image_url||x.imageUrl} alt={clean(x.title||'Priyasa')} loading={i<2?'eager':'lazy'}/>}<div><span>{clean(x.subtitle||'PRIYASA EDIT')}</span><strong>{clean(x.title||'Explore')}</strong>{(x.cta_label||x.ctaLabel)&&<small>{x.cta_label||x.ctaLabel} →</small>}</div></Link>)}</div>}
function Categories({categories,items}:{categories:StorefrontCategory[];items:any[]}){return <Cards items={items.length?items:categories.map(c=>({id:c.id,title:c.name,image_url:c.imageUrl,cta_href:`/shop?category=${encodeURIComponent(c.slug)}`}))}/>}
function Banner({s}:{s:HomeCmsSection}){return <section className="home-managed-banner"><div className="home-managed-banner-copy"><span>{clean(s.subtitle||'PRIYASA EDIT')}</span><h2>{clean(s.title||'The Priyasa Edit')}</h2>{(s.ctaHref||s.cta_href)&&<Link href={href(s)}>{label(s)} →</Link>}</div>{img(s)&&<picture>{(s.mobileImageUrl||s.mobile_image_url)&&<source media="(max-width:760px)" srcSet={String(s.mobileImageUrl||s.mobile_image_url)}/>}<img src={img(s)} alt={clean(s.title||'Priyasa fashion')} loading="lazy"/></picture>}</section>}
function TextBlock({s}:{s:HomeCmsSection}){return <section className="home-managed-text home-section"><span className="home-kicker">{clean(s.title||'PRIYASA')}</span><div className="home-rich-copy">{clean(s.content?.html||s.subtitle||'')}</div>{(s.ctaHref||s.cta_href)&&<Link className="button" href={href(s)}>{label(s)} →</Link>}</section>}
function Video({s}:{s:HomeCmsSection}){const url=s.content?.video_url||s.content?.videoUrl||img(s);if(!url)return null;return <section className="home-cms-video home-section"><video src={url} poster={img(s)||undefined} controls muted playsInline preload="metadata"/><div><span className="home-kicker">{clean(s.subtitle||'PRIYASA')}</span><h2>{clean(s.title||'Watch the latest edit')}</h2>{(s.ctaHref||s.cta_href)&&<Link className="button dark-button" href={href(s)}>{label(s)} →</Link>}</div></section>}
function Hero({s}:{s:HomeCmsSection}){const items=itemsOf(s);const slides=(items.length?items:[s]).map((x:any,i:number)=>({id:String(x.id||`${s.id}-${i}`),title:x.title||s.title,subtitle:x.subtitle||s.subtitle,imageUrl:x.image_url||x.imageUrl||img(s),mobileImageUrl:x.mobile_image_url||x.mobileImageUrl||s.mobile_image_url||s.mobileImageUrl||img(s),ctaLabel:x.cta_label||x.ctaLabel||label(s),ctaHref:x.cta_href||x.ctaHref||href(s)}));return <section className="home-section home-hero-multi home-managed-hero" data-testid="home-hero"><HomeHeroCarousel slides={slides}/></section>}
async function ProductSection({s}:{s:HomeCmsSection}){const c=s.content||{};const ids=Array.isArray(c.product_ids)?c.product_ids.map(String):[];let products:any[]=[];if(ids.length){const all=await getCachedStorefrontProducts({limit:100});products=ids.map((id:string)=>all.find((p:any)=>String(p.id)===id)).filter(Boolean);}else{const q=typeof c.query==='object'?c.query:{};const limit=Math.min(Math.max(Number(q.limit||12),1),30);const sort=String(q.sort||'');if(typeOf(s)==='new_arrivals')products=await getCachedStorefrontProducts({limit,sort:'newest'});else if(['trending','best_sellers'].includes(typeOf(s)))products=await getCachedStorefrontProducts({limit,sort:'popular'});else if(sort==='sale'||typeOf(s)==='flash_sale')products=await getProductsForHomeSection('sale',limit);else products=await getProductsForHomeSection(typeOf(s),limit);}if(!products.length)return null;return <section className="home-section home-product-section home-managed-products" key={s.id}><Heading s={s}/><HomeProductGrid products={products} initialVisible={Math.min(8,products.length)} step={8}/></section>}

export default async function DynamicHome({initialSections=[]}:{initialSections?:HomeCmsSection[]}){
 const sections=[...initialSections].filter(s=>s?.is_active!==false&&s?.isActive!==false).sort((a,b)=>sortOf(a)-sortOf(b)||Number(a.id)-Number(b.id));
 let categories:StorefrontCategory[]=[];
 if(sections.some(s=>typeOf(s)==='category_grid'))categories=await getStorefrontCategories();
 return <div className="home-reference-v5">{await Promise.all(sections.map(async(s:any)=>{const t=typeOf(s);const items=itemsOf(s);if(t==='hero_slider'||t==='hero'||t==='hero-slide')return <Hero s={s} key={s.id}/>;if(t==='category_grid')return <section className="home-section" key={s.id}><Heading s={s}/><Categories categories={categories} items={items}/></section>;if(['product_carousel','product_grid','flash_sale','trending','new_arrivals','best_sellers','products-sale','products-latest','products-best'].includes(t))return <ProductSection s={s}/>;if(t==='image_carousel')return <section className="home-section" key={s.id}><Heading s={s}/><HomeImageCarousel slides={items.map((x:any,i:number)=>({id:String(x.id||`${s.id}-${i}`),title:x.title,subtitle:x.subtitle,imageUrl:x.image_url||x.imageUrl,mobileImageUrl:x.mobile_image_url||x.mobileImageUrl,ctaLabel:x.cta_label||x.ctaLabel,ctaHref:x.cta_href||x.ctaHref||'/shop'}))}/></section>;if(['banner','offer'].includes(t))return <section className="home-section" key={s.id}><Banner s={s}/></section>;if(['collection_showcase','brand_grid'].includes(t))return <section className="home-section" key={s.id}><Heading s={s}/><Cards items={items}/></section>;if(t==='video')return <Video s={s} key={s.id}/>;if(t==='text')return <TextBlock s={s} key={s.id}/>;return <section className="home-section" key={s.id}><Heading s={s}/><Cards items={items}/></section>;}))}</div>;
}
