'use client';
import Link from 'next/link';import {useEffect,useRef,useState} from 'react';
type Slide={id:string;title?:string|null;subtitle?:string|null;imageUrl?:string|null;mobileImageUrl?:string|null;ctaLabel?:string|null;ctaHref?:string|null};
export default function HomeHeroCarousel({slides}:{slides:Slide[]}){
 const[active,setActive]=useState(0),[paused,setPaused]=useState(false);const startX=useRef<number|null>(null);const startY=useRef<number|null>(null);
 useEffect(()=>{if(slides.length<2||paused)return;const id=window.setInterval(()=>setActive(v=>(v+1)%slides.length),6000);return()=>window.clearInterval(id)},[slides.length,paused]);
 if(!slides.length)return null;
 const slide=slides[active];const next=()=>setActive(v=>(v+1)%slides.length);const prev=()=>setActive(v=>(v-1+slides.length)%slides.length);const image=slide.imageUrl||'/images/product-placeholder.svg';
 const touchStart=(e:React.TouchEvent)=>{const t=e.changedTouches[0];startX.current=t.clientX;startY.current=t.clientY};
 const touchEnd=(e:React.TouchEvent)=>{if(startX.current===null||startY.current===null)return;const t=e.changedTouches[0],dx=t.clientX-startX.current,dy=t.clientY-startY.current;startX.current=null;startY.current=null;if(Math.abs(dx)<45||Math.abs(dx)<Math.abs(dy))return;dx<0?next():prev()};
 return <section className="home-hero-carousel premium-home-hero" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setPaused(false)}} onTouchStart={touchStart} onTouchEnd={touchEnd} aria-roledescription="carousel" aria-label="Priyasa featured collections">
  <div className="home-hero-media"><img key={slide.id} src={image} alt={slide.title||'Priyasa collection'} onError={e=>{if(!e.currentTarget.src.endsWith('/product-placeholder.svg'))e.currentTarget.src='/images/product-placeholder.svg'}}/><div className="home-hero-shade"/></div>
  <div className="home-hero-copy"><span className="eyebrow">{slide.subtitle||'PRIYASA COLLECTIONS'}</span><h1>{slide.title||'Discover your style'}</h1>{slide.subtitle&&<p>{slide.subtitle}</p>}{slide.ctaHref&&<Link className="button" href={slide.ctaHref}>{slide.ctaLabel||'Shop Now'} →</Link>}</div>
  {slides.length>1&&<><button type="button" className="home-hero-control home-hero-prev" onClick={prev} aria-label="Previous slide">‹</button><button type="button" className="home-hero-control home-hero-next" onClick={next} aria-label="Next slide">›</button><div className="hero-slide-meta" aria-live="polite"><span>{String(active+1).padStart(2,'0')}</span><i/><span>{String(slides.length).padStart(2,'0')}</span></div><div className="home-hero-dots" role="tablist" aria-label="Featured slides">{slides.map((s,i)=><button type="button" key={s.id} className={i===active?'active':''} onClick={()=>setActive(i)} role="tab" aria-label={`Go to slide ${i+1}`} aria-selected={i===active}/>)}</div><div className="hero-progress" aria-hidden="true"><span style={{width:`${((active+1)/slides.length)*100}%`}}/></div></>}
 </section>
}

<style jsx global>{`
.premium-home-hero{position:relative!important;width:100%!important;max-width:100%!important;height:clamp(520px,calc(100vh - 72px),760px)!important;min-height:520px!important;margin:0!important;overflow:hidden!important;background:#f5efed!important;isolation:isolate!important;touch-action:pan-y!important}
.premium-home-hero .home-hero-media{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;overflow:hidden!important}
.premium-home-hero .home-hero-media img{display:block!important;width:100%!important;height:100%!important;max-width:none!important;object-fit:cover!important;object-position:center center!important;transition:transform .7s ease,opacity .25s ease!important}
.premium-home-hero:hover .home-hero-media img{transform:scale(1.008)!important}
.premium-home-hero .home-hero-shade{position:absolute!important;inset:0!important;pointer-events:none!important;background:linear-gradient(90deg,rgba(20,10,14,.58),rgba(20,10,14,.24) 36%,rgba(20,10,14,.03) 74%),linear-gradient(0deg,rgba(20,10,14,.36),transparent 52%)!important}
.premium-home-hero .home-hero-copy{position:absolute!important;left:clamp(34px,7vw,112px)!important;bottom:clamp(70px,10vh,112px)!important;z-index:4!important;width:min(620px,55vw)!important;max-width:620px!important;color:#fff!important;text-shadow:0 2px 20px rgba(0,0,0,.22)!important}
.premium-home-hero .home-hero-copy .eyebrow{display:block!important;color:#fff!important;font-size:10px!important;font-weight:700!important;letter-spacing:3.5px!important;text-transform:uppercase!important}
.premium-home-hero .home-hero-copy h1{margin:12px 0!important;color:#fff!important;font-size:clamp(46px,6.2vw,82px)!important;line-height:.98!important;letter-spacing:-3px!important;font-weight:500!important}
.premium-home-hero .home-hero-copy p{margin:0 0 18px!important;color:rgba(255,255,255,.9)!important;font-size:13px!important;line-height:1.55!important;max-width:470px!important}
.premium-home-hero .home-hero-copy .button{display:inline-flex!important;align-items:center!important;justify-content:center!important;min-height:48px!important;padding:0 26px!important;border-radius:4px!important;background:#f51b50!important;color:#fff!important;text-decoration:none!important;font-size:12px!important;font-weight:800!important;text-shadow:none!important;box-shadow:0 8px 24px rgba(0,0,0,.12)!important}
.premium-home-hero .home-hero-control{position:absolute!important;top:50%!important;z-index:6!important;display:grid!important;place-items:center!important;width:48px!important;height:48px!important;padding:0!important;border:1px solid rgba(255,255,255,.55)!important;border-radius:50%!important;background:rgba(255,255,255,.1)!important;color:#fff!important;transform:translateY(-50%)!important;font-size:31px!important;line-height:1!important;cursor:pointer!important;backdrop-filter:blur(8px)!important}
.premium-home-hero .home-hero-control:hover{background:rgba(255,255,255,.24)!important}.premium-home-hero .home-hero-prev{left:22px!important}.premium-home-hero .home-hero-next{right:22px!important}
.premium-home-hero .hero-slide-meta{position:absolute!important;right:clamp(22px,4vw,60px)!important;bottom:28px!important;z-index:6!important;display:flex!important;align-items:center!important;gap:10px!important;color:#fff!important;font-size:10px!important;font-weight:700!important;letter-spacing:1.2px!important}.premium-home-hero .hero-slide-meta i{width:28px!important;height:1px!important;background:rgba(255,255,255,.7)!important}
.premium-home-hero .home-hero-dots{position:absolute!important;left:50%!important;bottom:27px!important;z-index:6!important;display:flex!important;gap:6px!important;transform:translateX(-50%)!important}.premium-home-hero .home-hero-dots button{width:30px!important;height:3px!important;padding:0!important;border:0!important;border-radius:4px!important;background:#fff!important;opacity:.5!important;cursor:pointer!important;transition:width .2s,opacity .2s!important}.premium-home-hero .home-hero-dots button.active{width:52px!important;opacity:1!important}
.premium-home-hero .hero-progress{position:absolute!important;left:0!important;right:0!important;bottom:0!important;height:3px!important;z-index:7!important;background:rgba(255,255,255,.2)!important}.premium-home-hero .hero-progress span{display:block!important;height:100%!important;background:#fff!important;transition:width .35s ease!important}
@media(max-width:900px){
 .premium-home-hero{height:calc(100svh - 64px)!important;min-height:470px!important;max-height:720px!important}
 .premium-home-hero .home-hero-media img{object-position:center center!important;transform:none!important}
 .premium-home-hero .home-hero-shade{background:linear-gradient(180deg,rgba(20,10,14,.01) 12%,rgba(20,10,14,.08) 38%,rgba(20,10,14,.8) 100%)!important}
 .premium-home-hero .home-hero-copy{left:18px!important;right:18px!important;bottom:70px!important;width:auto!important;max-width:none!important}
 .premium-home-hero .home-hero-copy .eyebrow{font-size:8px!important;letter-spacing:3px!important}.premium-home-hero .home-hero-copy h1{font-size:clamp(34px,9.5vw,48px)!important;line-height:1.02!important;letter-spacing:-1.2px!important;margin:9px 0 11px!important;max-width:95%!important}.premium-home-hero .home-hero-copy p{font-size:11px!important;line-height:1.5!important;max-width:88%!important;margin-bottom:15px!important}.premium-home-hero .home-hero-copy .button{min-height:44px!important;padding:0 20px!important;font-size:11px!important}
 .premium-home-hero .home-hero-control{top:auto!important;bottom:70px!important;width:36px!important;height:36px!important;font-size:25px!important}.premium-home-hero .home-hero-prev{left:9px!important}.premium-home-hero .home-hero-next{right:9px!important}
 .premium-home-hero .home-hero-dots{left:18px!important;right:auto!important;bottom:23px!important;transform:none!important;gap:5px!important}.premium-home-hero .home-hero-dots button{width:20px!important;height:3px!important}.premium-home-hero .home-hero-dots button.active{width:34px!important}.premium-home-hero .hero-slide-meta{right:18px!important;bottom:20px!important;font-size:9px!important;gap:7px!important}.premium-home-hero .hero-slide-meta i{width:18px!important}
}
@media(max-width:480px){.premium-home-hero{height:calc(100svh - 64px)!important;min-height:460px!important;max-height:700px!important}.premium-home-hero .home-hero-copy{bottom:66px!important}.premium-home-hero .home-hero-control{bottom:68px!important;width:34px!important;height:34px!important}.premium-home-hero .home-hero-prev{left:7px!important}.premium-home-hero .home-hero-next{right:7px!important}}
`}</style>
