'use client';
import Link from 'next/link';import {useEffect,useRef,useState} from 'react';
type Slide={id:string;title?:string|null;subtitle?:string|null;imageUrl?:string|null;mobileImageUrl?:string|null;ctaLabel?:string|null;ctaHref?:string|null};
export default function HomeImageCarousel({slides}:{slides:Slide[]}){
 const[active,setActive]=useState(0),startX=useRef<number|null>(null),startY=useRef<number|null>(null);
 useEffect(()=>{if(slides.length<2)return;const id=window.setInterval(()=>setActive(v=>(v+1)%slides.length),5000);return()=>window.clearInterval(id)},[slides.length]);
 if(!slides.length)return null;const s=slides[active];const next=()=>setActive(v=>(v+1)%slides.length);const prev=()=>setActive(v=>(v-1+slides.length)%slides.length);
 const touchStart=(e:React.TouchEvent)=>{const t=e.changedTouches[0];startX.current=t.clientX;startY.current=t.clientY};
 const touchEnd=(e:React.TouchEvent)=>{if(startX.current===null||startY.current===null)return;const t=e.changedTouches[0],dx=t.clientX-startX.current,dy=t.clientY-startY.current;startX.current=null;startY.current=null;if(Math.abs(dx)<40||Math.abs(dx)<Math.abs(dy))return;dx<0?next():prev()};
 const imageError=(e:React.SyntheticEvent<HTMLImageElement>)=>{if(e.currentTarget.dataset.fallback)return;e.currentTarget.dataset.fallback='1';e.currentTarget.src='/images/product-placeholder.svg'};
 return <section className="home-image-carousel" onTouchStart={touchStart} onTouchEnd={touchEnd} aria-roledescription="carousel" aria-label="Priyasa collection images"><div className="home-image-carousel-media"><picture><source media="(max-width:720px)" srcSet={s.mobileImageUrl||s.imageUrl||'/images/product-placeholder.svg'}/><img src={s.imageUrl||'/images/product-placeholder.svg'} alt={s.title||'Priyasa collection'} onError={imageError}/></picture><div className="home-image-carousel-overlay"><span className="eyebrow">{s.subtitle||'PRIYASA EDIT'}</span><h2>{s.title||'Made for your moment'}</h2>{s.ctaHref&&<Link className="button" href={s.ctaHref}>{s.ctaLabel||'Explore'} →</Link>}</div>{slides.length>1&&<><button type="button" className="home-image-carousel-control prev" onClick={prev} aria-label="Previous image">‹</button><button type="button" className="home-image-carousel-control next" onClick={next} aria-label="Next image">›</button></>}</div>{slides.length>1&&<div className="home-image-carousel-dots" role="tablist" aria-label="Collection images">{slides.map((x,i)=><button type="button" key={x.id} className={i===active?'active':''} onClick={()=>setActive(i)} aria-label={`Show image ${i+1}`} aria-selected={i===active} role="tab"/> )}</div>}</section>}
