'use client';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {AddToCart} from '@/components/AddToCart';

type Variant={id:string;color:string;size:string;price:number;stock:number};
type Product={id:string;name:string;price:number;colors:string[];sizes:string[];image?:string;variants?:Variant[]};
export function ProductPurchase({product}:{product:Product}){
 const router=useRouter();const [color,setColor]=useState(product.colors[0]||'');const [size,setSize]=useState(product.sizes[0]||'');const [qty,setQty]=useState(1);
 const variant=useMemo(()=>product.variants?.find(v=>v.color===color&&v.size===size&&v.stock>0)||product.variants?.find(v=>v.stock>0),[product.variants,color,size]);
 const price=variant?.price??product.price;
 function addBuy(){if(!variant)return;const key='priyasa_cart';const cart=JSON.parse(localStorage.getItem(key)||'[]');const i=cart.findIndex((x:any)=>x.variantId===variant.id);const item={variantId:variant.id,productId:product.id,name:`${product.name} · ${variant.color} · ${variant.size}`,price,image:product.image,quantity:qty};if(i>=0)cart[i]={...cart[i],quantity:Math.min(20,cart[i].quantity+qty)};else cart.push(item);localStorage.setItem(key,JSON.stringify(cart));window.dispatchEvent(new Event('priyasa-cart-updated'));router.push('/checkout');}
 return <div className="purchase-panel"><div className="option-block"><div className="option-label"><strong>Color</strong><span>{color}</span></div><div className="color-options">{product.colors.map(c=><button type="button" key={c} aria-label={c} title={c} className={`color-chip color-${c.toLowerCase().replaceAll(' ','-')} ${color===c?'active':''}`} onClick={()=>setColor(c)}>{<span/>}</button>)}</div></div><div className="option-block"><div className="option-label"><strong>Size</strong><a className="size-guide-link" href="/size-guide">Size Guide ↗</a></div><div className="size-options">{product.sizes.map(s=>{const available=product.variants?.some(v=>v.color===color&&v.size===s&&v.stock>0);return <button type="button" disabled={available===false} key={s} className={size===s?'active':''} onClick={()=>setSize(s)}>{s}</button>})}</div></div><div className="quantity-row"><strong>Quantity</strong><div className="qty-control"><button type="button" onClick={()=>setQty(Math.max(1,qty-1))}>−</button><span>{qty}</span><button type="button" onClick={()=>setQty(Math.min(20,qty+1))}>+</button></div></div><div className="purchase-actions"><AddToCart variantId={variant?.id||''} productId={product.id} name={`${product.name} · ${color} · ${size}`} price={price} image={product.image}/><button type="button" className="button dark-button" onClick={addBuy} disabled={!variant||variant.stock<qty}>Buy it now</button></div><div className="purchase-trust"><span>✓ Secure payment</span><span>✓ Easy returns</span><span>✓ Quality checked</span></div></div>;
}
