'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import type {Product} from '@/lib/catalog';import {money} from '@/lib/catalog';import {AddToCart} from '@/components/AddToCart';import {SafeImage} from '@/components/SafeImage';

export function ProductCard({product}:{product:Product}){
 const [liked,setLiked]=useState(false),[auth,setAuth]=useState(false),[quick,setQuick]=useState(false);
 useEffect(()=>{fetch('/api/customer/wishlist',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.authenticated){setAuth(true);setLiked((d.data||[]).some((x:any)=>x.id===product.id));}else{try{setLiked(JSON.parse(localStorage.getItem('priyasa_wishlist')||'[]').includes(product.id));}catch{}}}).catch(()=>{try{setLiked(JSON.parse(localStorage.getItem('priyasa_wishlist')||'[]').includes(product.id));}catch{}})},[product.id]);
 async function toggleWishlist(){if(auth){const next=!liked;setLiked(next);const r=await fetch(`/api/customer/wishlist${next?'':'?productId='+encodeURIComponent(product.id)}`,{method:next?'POST':'DELETE',headers:{'Content-Type':'application/json'},body:next?JSON.stringify({productId:product.id}):undefined});if(!r.ok)setLiked(!next);return}const key='priyasa_wishlist';const list:string[]=JSON.parse(localStorage.getItem(key)||'[]');const next=liked?list.filter(id=>id!==product.id):[...new Set([...list,product.id])];localStorage.setItem(key,JSON.stringify(next));setLiked(!liked)}
 const hasDiscount=Number(product.mrp)>Number(product.price)&&Number(product.price)>0;
 const discount=hasDiscount?Math.max(1,Math.round((1-Number(product.price)/Number(product.mrp))*100)):0;
 useEffect(()=>{try{const key='priyasa_recently_viewed';const list:string[]=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([product.id,...list.filter(id=>id!==product.id)].slice(0,20)))}catch{}},[product.id]);
 return <article className="product-card"><div className="product-media">{discount>0&&<span className="discount-badge product-discount-badge" data-discount={discount} aria-label={`${discount}% discount`}>{discount}% OFF</span>}{product.badge&&<span className="badge">{product.badge}</span>}<button className={`product-wishlist ${liked?'liked':''}`} onClick={toggleWishlist} aria-label={liked?'Remove from wishlist':'Add to wishlist'}>{liked?'♥':'♡'}</button><Link href={`/product/${product.slug}`} aria-label={product.name} className="product-image-link"><SafeImage src={product.image} alt={product.name} width={600} height={800}/></Link><button type="button" className="product-quick-view" onClick={()=>setQuick(true)}>Quick View</button>{product.variantId&&<div className="quick-add"><AddToCart variantId={product.variantId} productId={product.id} name={product.name} price={product.price} image={product.image}/></div>}</div><div className="product-info"><div className="product-category">{product.category}</div><h3><Link href={`/product/${product.slug}`}>{product.name}</Link></h3>{typeof product.rating==='number'&&product.reviewCount!==undefined&&product.reviewCount>0&&<div className="product-rating"><span>★★★★★</span> <small>{product.rating.toFixed(1)} ({product.reviewCount})</small></div>}<div><span className="price">{money(product.price)}</span>{hasDiscount&&<> <span className="mrp">{money(product.mrp)}</span><span className="discount-text">{discount}% off</span></>}</div></div>
 {quick&&<div className="quick-view-backdrop" role="dialog" aria-modal="true" aria-label={`Quick view ${product.name}`} onClick={()=>setQuick(false)}><div className="quick-view-card" onClick={e=>e.stopPropagation()}><button className="quick-view-close" type="button" onClick={()=>setQuick(false)} aria-label="Close quick view">×</button><div className="quick-view-image"><SafeImage src={product.image} alt={product.name} width={600} height={800}/></div><div className="quick-view-copy"><span className="product-category">{product.category}</span><h2>{product.name}</h2>{product.rating&&product.reviewCount?<div className="product-rating">★★★★★ <small>{product.rating.toFixed(1)} ({product.reviewCount})</small></div>:null}<div className="quick-view-price"><b>{money(product.price)}</b>{hasDiscount&&<><del>{money(product.mrp)}</del><strong>{discount}% OFF</strong></>}</div>{product.sizes.length>0&&<p><b>Sizes:</b> {product.sizes.join(' · ')}</p>}{product.colors.length>0&&<p><b>Colours:</b> {product.colors.join(' · ')}</p>}<Link className="button dark-button" href={`/product/${product.slug}`} onClick={()=>setQuick(false)}>View Product →</Link></div></div></div>}
 </article>
}
