'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import type {Product} from '@/lib/catalog';import {money} from '@/lib/catalog';import {AddToCart} from '@/components/AddToCart';import {SafeImage} from '@/components/SafeImage';

export function ProductCard({product}:{product:Product}){
 const [liked,setLiked]=useState(false),[auth,setAuth]=useState(false);
 useEffect(()=>{fetch('/api/customer/wishlist',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.authenticated){setAuth(true);setLiked((d.data||[]).some((x:any)=>x.id===product.id));}else{try{setLiked(JSON.parse(localStorage.getItem('priyasa_wishlist')||'[]').includes(product.id));}catch{}}}).catch(()=>{try{setLiked(JSON.parse(localStorage.getItem('priyasa_wishlist')||'[]').includes(product.id));}catch{}})},[product.id]);
 async function toggleWishlist(){if(auth){const next=!liked;setLiked(next);const r=await fetch(`/api/customer/wishlist${next?'':'?productId='+encodeURIComponent(product.id)}`,{method:next?'POST':'DELETE',headers:{'Content-Type':'application/json'},body:next?JSON.stringify({productId:product.id}):undefined});if(!r.ok)setLiked(!next);return}const key='priyasa_wishlist';const list:string[]=JSON.parse(localStorage.getItem(key)||'[]');const next=liked?list.filter(id=>id!==product.id):[...new Set([...list,product.id])];localStorage.setItem(key,JSON.stringify(next));setLiked(!liked)}
 const discount=product.mrp>product.price?Math.round((1-product.price/product.mrp)*100):0;
 return <article className="product-card"><div className="product-media">{discount>0&&<span className="discount-badge" aria-label={`${discount}% discount`}>{discount}% OFF</span>}{product.badge&&<span className="badge">{product.badge}</span>}<button className={`product-wishlist ${liked?'liked':''}`} onClick={toggleWishlist} aria-label={liked?'Remove from wishlist':'Add to wishlist'}>{liked?'♥':'♡'}</button><Link href={`/product/${product.slug}`} aria-label={product.name} className="product-image-link"><SafeImage src={product.image} alt={product.name} width={600} height={800}/></Link>{product.variantId&&<div className="quick-add"><AddToCart variantId={product.variantId} productId={product.id} name={product.name} price={product.price} image={product.image}/></div>}</div><div className="product-info"><div className="product-category">{product.category}</div><h3><Link href={`/product/${product.slug}`}>{product.name}</Link></h3>{typeof product.rating==='number'&&product.reviewCount!==undefined&&product.reviewCount>0&&<div className="product-rating"><span>★★★★★</span> <small>{product.rating.toFixed(1)} ({product.reviewCount})</small></div>}<div><span className="price">{money(product.price)}</span>{product.mrp>product.price&&<> <span className="mrp">{money(product.mrp)}</span>{discount>0&&<span className="discount-text">{discount}% off</span>}</>}</div></div></article>
}
