'use client';
import {useState} from 'react';
type Summary={categories:number;products:number;variableProducts?:number;variations:number;variants?:number;images?:number;skipped?:number;deactivatedStaleProducts?:number};
export default function WooCommerceImportPanel(){
 const [summary,setSummary]=useState<Summary|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function preview(){setBusy(true);setMessage('Connecting to WooCommerce and reading the live catalog…');try{const r=await fetch('/api/admin/catalog/woocommerce',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Preview failed');setSummary(j.data);setMessage('Preview complete. No database changes were made.');}catch(e){setMessage(e instanceof Error?e.message:'Preview failed');}finally{setBusy(false);}}
 async function run(mode:'import'|'sync'){const text=mode==='sync'?'Sync the live WooCommerce catalog with Priyasa now? Products missing from WooCommerce will be deactivated only when the complete sync succeeds. WooCommerce itself will not be changed.':'Import the live WooCommerce catalog into Priyasa now? Existing products with matching slugs/SKUs will be updated.';if(!confirm(text))return;setBusy(true);setMessage(mode==='sync'?'Synchronizing categories, products, variants and images…':'Importing categories, products, variants and images…');try{const r=await fetch('/api/admin/catalog/woocommerce',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});const j=await r.json();if(!r.ok)throw new Error(j.error||`${mode} failed`);setSummary(j.data);setMessage(mode==='sync'?'WooCommerce sync completed successfully.':'Import completed. Review Products and Categories.');}catch(e){setMessage(e instanceof Error?e.message:`${mode} failed`);}finally{setBusy(false);}}
 return <div className="card" style={{maxWidth:980}}><div style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:18}}><button className="button" onClick={preview} disabled={busy}>Preview Live Catalog</button><button className="button" onClick={()=>run('import')} disabled={busy||!summary}>Import into Priyasa DB</button><button className="button dark-button" onClick={()=>run('sync')} disabled={busy||!summary}>Sync WooCommerce → Priyasa</button></div>{message&&<p className="muted">{message}</p>}{summary&&<div className="grid-3" style={{marginTop:18}}>{[['Categories',summary.categories],['Products',summary.products],['Variations',summary.variations??summary.variants??0],['Images',summary.images??0],['Variable Products',summary.variableProducts??0],['Skipped',summary.skipped??0],['Deactivated Stale',summary.deactivatedStaleProducts??0]].map(([label,value])=><div className="card" key={String(label)}><strong>{label}</strong><div style={{fontSize:28,fontWeight:800,marginTop:6}}>{value}</div></div>)}</div>}<div style={{marginTop:22,padding:16,border:'1px solid #e5e7eb',borderRadius:12}}><strong>Migration & sync behavior</strong><ul><li>WooCommerce remains untouched.</li><li>Products match by slug and variants by SKU, so repeated operations update instead of duplicating.</li><li>Published products are activated; hidden/non-published products are imported as inactive.</li><li>Prices are converted into Priyasa integer rupee fields and WooCommerce stock is mirrored.</li><li>Sync deactivates stale Priyasa products only after the full WooCommerce read completes without skipped products.</li></ul></div></div>;
}
