'use client';
import {useState} from 'react';

type Summary={categories:number;products:number;variableProducts?:number;variations:number;variants?:number;images?:number;skipped?:number};
export default function WooCommerceImportPanel(){
 const [summary,setSummary]=useState<Summary|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function preview(){setBusy(true);setMessage('Connecting to WooCommerce and reading the live catalog…');try{const r=await fetch('/api/admin/catalog/woocommerce');const j=await r.json();if(!r.ok)throw new Error(j.error||'Preview failed');setSummary(j.data);setMessage('Preview complete. No database changes were made.');}catch(e){setMessage(e instanceof Error?e.message:'Preview failed');}finally{setBusy(false);}}
 async function run(){if(!confirm('Import the live WooCommerce catalog into Priyasa now? Existing products with matching slugs/SKUs will be updated. WooCommerce will not be changed.'))return;setBusy(true);setMessage('Importing categories, products, variants and images…');try{const r=await fetch('/api/admin/catalog/woocommerce',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'import'})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Import failed');setSummary(j.data);setMessage('Import completed. Review Products and Categories before switching traffic.');}catch(e){setMessage(e instanceof Error?e.message:'Import failed');}finally{setBusy(false);}}
 return <div className="card" style={{maxWidth:900}}><div style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:18}}><button className="button" onClick={preview} disabled={busy}>Preview Live Catalog</button><button className="button dark-button" onClick={run} disabled={busy||!summary}>Import into Priyasa DB</button></div>{message&&<p className="muted">{message}</p>}{summary&&<div className="grid-3" style={{marginTop:18}}>{[['Categories',summary.categories],['Products',summary.products],['Variations',summary.variations??summary.variants??0],['Images',summary.images??0],['Variable Products',summary.variableProducts??0],['Skipped',summary.skipped??0]].map(([label,value])=><div className="card" key={String(label)}><strong>{label}</strong><div style={{fontSize:28,fontWeight:800,marginTop:6}}>{value}</div></div>)}</div>}<div style={{marginTop:22,padding:16,border:'1px solid #e5e7eb',borderRadius:12}}><strong>Migration behavior</strong><ul><li>WooCommerce remains untouched.</li><li>Products are matched by slug and variants by SKU, so repeated imports update instead of duplicating.</li><li>Published products are activated; hidden/non-published products are imported as inactive.</li><li>WooCommerce prices are converted from decimal currency values into Priyasa's integer rupee fields.</li></ul></div></div>;
}
