'use client';
import Link from 'next/link';import {useEffect,useRef,useState} from 'react';

type Section={id?:string;key:string;type:string;title?:string|null;subtitle?:string|null;imageUrl?:string|null;mobileImageUrl?:string|null;ctaLabel?:string|null;ctaHref?:string|null;startsAt?:string|null;endsAt?:string|null;active:boolean;sortOrder:number};
type Media={name:string;url:string;size:number;updatedAt:string};
type Target={id:string;name:string;slug:string};
const blank:Section={key:'home.section.new',type:'hero-slide',title:'',subtitle:'',imageUrl:'',mobileImageUrl:'',ctaLabel:'Shop now',ctaHref:'/shop',startsAt:'',endsAt:'',active:true,sortOrder:0};
const presets:[string,string][]=[['hero-slide','Hero slider slide'],['image-carousel','Image carousel slide'],['banner','Image banner'],['feature','Feature section'],['promo','Promotion banner'],['category-grid','Shop by category'],['products-latest','Latest products'],['products-best','Best sellers'],['products-sale','Sale favourites'],['products-category:festival','Festival collection'],['products-category:women','Category products'],['text','Text / editorial']];
const labels=new Map(presets);
function targetFromHref(href?:string|null){if(href?.startsWith('/product/'))return ['product',href.slice(9)] as const;if(href?.startsWith('/category/'))return ['category',href.slice(9)] as const;return ['custom',href||'/shop'] as const}
function Preview({form}:{form:Section}){const type=form.type.toLowerCase();return <div className="cms-preview"><div className="cms-preview-browser"><span/> <span/> <span/><b>PRIYASA • Live Preview</b></div>{['hero-slide','image-carousel'].includes(type)?<div className="cms-preview-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(35,14,19,.66),rgba(35,14,19,.08)),url(${form.imageUrl||'/images/product-placeholder.svg'})`}}><div><small>{form.subtitle||'PRIYASA COLLECTIONS'}</small><h2>{form.title||'Your headline'}</h2>{form.ctaHref&&<button>{form.ctaLabel||'Shop now'} →</button>}</div></div>:<div className="cms-preview-section"><small>{form.subtitle||'PRIYASA EDIT'}</small><h2>{form.title||'Section title'}</h2>{form.imageUrl&&<img src={form.imageUrl} alt="Preview"/>}<button>{form.ctaLabel||'View All'} →</button></div>}</div>}
export default function Cms(){const [rows,setRows]=useState<Section[]>([]);const [form,setForm]=useState<Section>(blank);const [media,setMedia]=useState<Media[]>([]);const [products,setProducts]=useState<Target[]>([]);const [categories,setCategories]=useState<Target[]>([]);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const [dragId,setDragId]=useState<string|null>(null);const fileRef=useRef<HTMLInputElement>(null);const [targetType,targetValue]=targetFromHref(form.ctaHref);
 async function load(){const [r,m,p,c]=await Promise.all([fetch('/api/admin/cms',{cache:'no-store'}),fetch('/api/admin/cms/media',{cache:'no-store'}),fetch('/api/admin/products',{cache:'no-store'}),fetch('/api/admin/categories',{cache:'no-store'})]);const d=await r.json();const md=await m.json();const pd=await p.json();const cd=await c.json();if(r.ok)setRows(d.data||[]);if(m.ok)setMedia(md.data||[]);if(p.ok)setProducts((pd.data||[]).map((x:any)=>({id:x.id,name:x.name,slug:x.slug})));if(c.ok)setCategories((cd.data||[]).map((x:any)=>({id:x.id,name:x.name,slug:x.slug})))}useEffect(()=>{load()},[]);
 function edit(x:Section){setForm({...x,startsAt:x.startsAt?x.startsAt.slice(0,16):'',endsAt:x.endsAt?x.endsAt.slice(0,16):''});window.scrollTo({top:0,behavior:'smooth'})}
 function setTarget(kind:string,value:string){setForm(f=>({...f,ctaHref:kind==='product'?`/product/${value}`:kind==='category'?`/category/${value}`:value}))}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');try{const r=await fetch('/api/admin/cms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,sortOrder:Number(form.sortOrder),startsAt:form.startsAt||undefined,endsAt:form.endsAt||undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save');setMsg(form.type==='hero-slide'?'Slider slide published.':form.type==='banner'?'Image banner published.':form.type==='feature'?'Feature section published.':'Homepage section saved.');setForm({...blank,key:`home.section.${Date.now()}`,sortOrder:rows.length*10});await load()}catch(e){setMsg(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 async function upload(file:File){setBusy(true);setMsg('Uploading media…');try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/cms/media',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'Upload failed');setForm(f=>({...f,imageUrl:d.data.url}));setMsg('Media uploaded.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}}
 async function removeMedia(name:string){if(!confirm('Delete this media file? Existing sections using it may show a broken image.'))return;await fetch(`/api/admin/cms/media?name=${encodeURIComponent(name)}`,{method:'DELETE'});await load()}
 async function reorder(next:Section[]){setRows(next);const r=await fetch('/api/admin/cms/reorder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:next.map(x=>x.id).filter(Boolean)})});if(!r.ok)setMsg('Unable to save the new order.');else setMsg('Homepage order saved.')}
 function drop(targetId:string){if(!dragId||dragId===targetId)return;const next=[...rows];const from=next.findIndex(x=>x.id===dragId);const to=next.findIndex(x=>x.id===targetId);if(from<0||to<0)return;const [moved]=next.splice(from,1);next.splice(to,0,moved);setDragId(null);void reorder(next)}
 async function removeSection(id?:string){if(!id||!confirm('Remove this homepage section?'))return;const r=await fetch(`/api/admin/cms?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(!r.ok){setMsg('Unable to delete section.');return}setMsg('Section removed.');await load()}
 return <div className="admin-shell"><aside className="admin-nav"><h2>PRIYASA</h2><Link href="/admin">← Dashboard</Link><Link href="/admin/cms">Homepage Studio</Link><Link href="/admin/products">Products</Link><Link href="/admin/categories">Categories</Link><Link href="/admin/orders">Orders</Link><Link href="/admin/marketing">Marketing</Link></aside><section className="admin-main">
  <div className="section-head"><div><h1>Homepage Studio</h1><p className="muted">Manage sliders, image banners, feature sections and product/category links without code.</p></div><button className="button" onClick={()=>setForm({...blank,key:`home.section.${Date.now()}`,sortOrder:rows.length*10})}>+ Add section</button></div>
  {msg&&<div className="checkout-status">{msg}</div>}
  <div className="cms-studio-grid"><div>
   <form className="admin-card admin-form" onSubmit={save}><div className="admin-card-head"><div><h2>{form.id?'Edit section':'New homepage section'}</h2><p className="muted">Choose a content type, image and destination. Schedule it or turn it off without deleting it.</p></div></div><div className="admin-form-grid">
    <label>Section type<select className="input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{presets.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Internal key<input className="input" required value={form.key} onChange={e=>setForm({...form,key:e.target.value})}/></label><label>Title<input className="input" value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Subtitle / eyebrow<input className="input" value={form.subtitle||''} onChange={e=>setForm({...form,subtitle:e.target.value})}/></label>
    <label className="full-span">Desktop image<div className="cms-media-field"><input className="input" type="url" value={form.imageUrl||''} onChange={e=>setForm({...form,imageUrl:e.target.value})}/><button type="button" className="button" onClick={()=>fileRef.current?.click()}>Upload</button></div></label><label className="full-span">Mobile image URL<input className="input" type="url" value={form.mobileImageUrl||''} onChange={e=>setForm({...form,mobileImageUrl:e.target.value})}/></label><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp,image/avif,image/gif" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value=''}}/>
    <label>Button label<input className="input" value={form.ctaLabel||''} onChange={e=>setForm({...form,ctaLabel:e.target.value})}/></label><label>Link type<select className="input" value={targetType} onChange={e=>setTarget(e.target.value,e.target.value==='custom'?form.ctaHref||'/shop':String(targetValue||''))}><option value="custom">Custom URL</option><option value="product">Product</option><option value="category">Category</option></select></label>
    {targetType==='product'?<label>Product<select className="input" value={targetValue} onChange={e=>setTarget('product',e.target.value)}><option value="">Select product</option>{products.map(x=><option key={x.id} value={x.slug}>{x.name}</option>)}</select></label>:targetType==='category'?<label>Category<select className="input" value={targetValue} onChange={e=>setTarget('category',e.target.value)}><option value="">Select category</option>{categories.map(x=><option key={x.id} value={x.slug}>{x.name}</option>)}</select></label>:<label>Destination URL<input className="input" value={form.ctaHref||''} onChange={e=>setTarget('custom',e.target.value)}/></label>}
    <label>Start time<input className="input" type="datetime-local" value={form.startsAt||''} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>End time<input className="input" type="datetime-local" value={form.endsAt||''} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label><label>Sort order<input className="input" type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/></label><label className="push-consent"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Published / active</label>
   </div><div style={{display:'flex',gap:10,marginTop:18}}><button className="button dark-button" disabled={busy}>{busy?'Saving…':form.id?'Update section':'Publish section'}</button>{form.id&&<button type="button" className="button" onClick={()=>setForm(blank)}>Cancel edit</button>}</div></form>
   <div className="admin-card" style={{marginTop:20}}><div className="admin-card-head"><div><h2>Homepage structure</h2><p className="muted">Drag to reorder live content. Multiple hero slides become the storefront slider.</p></div></div><div className="cms-section-list">{rows.map((x,i)=><div key={x.id||x.key} className={`cms-section-row ${x.active?'':'is-disabled'}`} draggable onDragStart={()=>setDragId(x.id||null)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(x.id||'')}><span className="cms-drag">⋮⋮</span><span className="cms-order">{i+1}</span>{x.imageUrl?<img src={x.imageUrl} alt=""/>:<div className="cms-thumb-empty">{x.type.slice(0,1).toUpperCase()}</div>}<div className="cms-row-copy"><b>{x.title||'Untitled section'}</b><small>{labels.get(x.type)||x.type} · {x.ctaHref||'No link'}</small></div><span className={`cms-status ${x.active?'on':''}`}>{x.active?'LIVE':'OFF'}</span><button className="button" onClick={()=>edit(x)}>Edit</button><button className="button" onClick={()=>removeSection(x.id)}>Delete</button></div>)}</div>{!rows.length&&<div className="empty">No homepage sections yet.</div>}</div>
  </div><aside><Preview form={form}/><div className="admin-card cms-media-library"><div className="admin-card-head"><div><h2>Media library</h2><p className="muted">Upload reusable campaign images.</p></div><button className="button" onClick={()=>fileRef.current?.click()}>+ Upload</button></div><div className="cms-media-grid">{media.map(m=><div className="cms-media-item" key={m.name}><img src={m.url} alt=""/><button type="button" title="Use image" onClick={()=>setForm(f=>({...f,imageUrl:m.url}))}>Use</button><button type="button" title="Delete image" onClick={()=>void removeMedia(m.name)}>×</button></div>)}</div>{!media.length&&<div className="empty">No CMS media uploaded yet.</div>}</div><div className="admin-card cms-recipes"><h2>Dynamic building blocks</h2><ul><li><b>Slider</b> — add multiple Hero slider slides with product/category/custom links.</li><li><b>Image banner</b> — desktop + mobile creative with scheduling.</li><li><b>Feature section</b> — image, title, copy and CTA.</li><li><b>Product collections</b> — latest, best sellers, sale or category-driven.</li><li><b>Publishing</b> — drag order, activate/deactivate and schedule campaigns.</li></ul></div></aside></div>
 </section></div>}
