'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';
type C={id:string;name:string;slug:string;description?:string|null;imageUrl?:string|null;parentId?:string|null;_count?:{products:number}};
const empty={name:'',slug:'',description:'',imageUrl:'',parentId:''};
export default function CategoriesAdmin(){const [rows,setRows]=useState<C[]>([]);const [form,setForm]=useState(empty);const [editId,setEditId]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/categories',{cache:'no-store'});const d=await r.json();if(r.ok)setRows(d.data||[]);else setMsg(d.error||'Unable to load categories')}useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');try{const r=await fetch(editId?`/api/admin/categories/${editId}`:'/api/admin/categories',{method:editId?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(!editId&&r.redirected){location.reload();return}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to save category');setMsg(editId?'Category updated.':'Category created.');setForm(empty);setEditId('');await load()}catch(e){setMsg(e instanceof Error?e.message:'Unable to save category')}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm('Delete this category? It must have no products or child categories.'))return;const r=await fetch(`/api/admin/categories/${id}`,{method:'DELETE'});const d=await r.json();if(!r.ok){setMsg(d.error||'Unable to delete');return}setMsg('Category deleted.');await load()}
 return <div className="admin-shell"><aside className="admin-nav"><h2>PRIYASA Admin</h2><Link href="/admin">← Dashboard</Link><Link href="/admin/products">Products</Link><Link href="/admin/categories">Categories</Link><Link href="/admin/inventory">Inventory</Link><Link href="/admin/coupons-offers">Offers & Coupons</Link></aside><section className="admin-main"><div className="section-head"><div><span className="eyebrow dark">CATALOG MANAGEMENT</span><h1>Categories</h1><p className="muted">Create, edit, organize and safely remove storefront categories.</p></div><Link className="button dark-button" href="/admin/products">Manage Products →</Link></div>{msg&&<div className="checkout-status">{msg}</div>}<form onSubmit={save} className="admin-card admin-form" style={{marginBottom:24}}><div className="admin-card-head"><div><h2>{editId?'Edit category':'Add category'}</h2><p className="muted">Category links can be used directly from Homepage Studio.</p></div></div><div className="admin-form-grid"><label>Name<input className="input" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Slug<input className="input" required pattern="[a-z0-9-]+" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Parent category<select className="input" value={form.parentId} onChange={e=>setForm({...form,parentId:e.target.value})}><option value="">Top level</option>{rows.filter(x=>x.id!==editId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Image URL<input className="input" type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></label><label className="full-span">Description<textarea className="input" rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div style={{display:'flex',gap:10,marginTop:16}}><button className="button dark-button" disabled={busy}>{busy?'Saving…':editId?'Update category':'Add category'}</button>{editId&&<button type="button" className="button" onClick={()=>{setEditId('');setForm(empty)}}>Cancel</button>}</div></form><div className="table-wrap"><table className="table"><thead><tr><th>Category</th><th>Slug</th><th>Parent</th><th>Products</th><th>Actions</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><strong>{c.name}</strong>{c.imageUrl&&<><br/><small>Image configured</small></>}</td><td>{c.slug}</td><td>{rows.find(x=>x.id===c.parentId)?.name||'—'}</td><td>{c._count?.products||0}</td><td><button className="button" onClick={()=>{setEditId(c.id);setForm({name:c.name,slug:c.slug,description:c.description||'',imageUrl:c.imageUrl||'',parentId:c.parentId||''});window.scrollTo({top:0,behavior:'smooth'})}}>Edit</button> <button className="button" onClick={()=>void remove(c.id)}>Delete</button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="empty" style={{marginTop:22}}>No categories yet.</div>}</section></div>}
