import { test, expect, devices } from '@playwright/test';

const publicRoutes = ['/', '/shop', '/about', '/contact', '/shipping-policy', '/return-refund-policy', '/privacy-policy', '/terms-and-conditions', '/cancellation-policy', '/faq', '/app', '/track-order', '/checkout'];
const adminControlRoutes = ['/admin/orders','/admin/products','/admin/inventory','/admin/customers','/admin/marketing','/admin/automations','/admin/analytics','/admin/returns-refunds','/admin/cms','/admin/settings','/admin/reviews','/admin/seo','/admin/coupons-offers','/admin/products/woocommerce','/admin/products/import','/admin/meta-ads','/admin/whatsapp','/admin/audit-log'];

test('public customer routes are reachable', async ({ page }) => { for (const route of publicRoutes) { const response=await page.goto(route,{waitUntil:'domcontentloaded'}); expect(response?.status(),`${route} returned an HTTP error`).toBeLessThan(500); await expect(page.locator('body')).not.toContainText('Application error'); } });
test('storefront and checkout entry are reachable', async ({ page }) => { await page.goto('/'); await expect(page).toHaveTitle(/Priyasa/i); await page.goto('/shop'); await expect(page.locator('body')).toContainText(/All styles|Shop/i); await page.goto('/checkout'); await expect(page.locator('body')).toContainText(/Sign in to continue|Shipping address/i); });
test('product discovery has real product links', async ({ page }) => { await page.goto('/shop'); const productLinks=page.locator('a[href*="/product/"]'); await expect(productLinks.first()).toBeVisible({timeout:10000}); const href=await productLinks.first().getAttribute('href'); expect(href).toMatch(/^\/product\/.+/); await page.goto(href!); await expect(page.locator('body')).not.toContainText('Application error'); });
test('customer login is mobile OTP only', async ({ page }) => { await page.goto('/login'); await expect(page.locator('body')).toContainText(/Sign in with mobile|Continue with Mobile/i); const main=page.locator('main').first(); await expect(main).not.toContainText('Google'); await expect(main).not.toContainText('Facebook'); });
test('customer order and payment routes are present', async ({ page }) => { await page.goto('/account/orders'); await expect(page.locator('body')).toContainText(/My Orders|Sign in/i); await page.goto('/track-order'); await expect(page.locator('body')).toContainText(/Track Your Order/i); });
test('invalid checkout confirmation cannot expose an order', async ({ page }) => { const response=await page.goto('/checkout/success?order=invalid-e2e-order'); expect(response?.status()).toBeLessThan(500); await expect(page.locator('body')).not.toContainText('Application error'); });
test('cart persistence and quote validation are non-destructive', async ({ page }) => { await page.addInitScript(()=>{localStorage.setItem('priyasa_cart','[]')}); await page.goto('/cart'); await expect(page.locator('body')).toContainText(/Shopping bag|Your bag is waiting/i); await page.reload(); await expect(page.locator('body')).not.toContainText('Application error'); const quoteResponse=await page.request.post('/api/checkout/quote',{data:{items:[]}}); expect(quoteResponse.status()).toBeLessThan(500); });
test('admin redirects unauthenticated visitors', async ({ page }) => { await page.goto('/admin'); await expect(page).toHaveURL(/admin\/login/); });
test('all admin control routes are guarded without server errors', async ({ page }) => { for (const route of adminControlRoutes) { const response=await page.goto(route,{waitUntil:'domcontentloaded'}); expect(response?.status(),`${route} returned an HTTP error`).toBeLessThan(500); await expect(page).toHaveURL(/admin\/login/); await expect(page.locator('body')).not.toContainText('Application error'); } });
test.describe('mobile app-like navigation',()=>{ test.use({viewport:devices['iPhone 13'].viewport,userAgent:devices['iPhone 13'].userAgent,isMobile:true}); test('mobile home exposes bottom navigation and usable touch targets',async({page})=>{await page.goto('/');await expect(page.locator('nav').last()).toBeVisible();const links=page.locator('a');const count=await links.count();expect(count).toBeGreaterThan(0);for(let i=0;i<Math.min(count,20);i+=1){const box=await links.nth(i).boundingBox();if(box)expect(box.height).toBeGreaterThanOrEqual(24)}});test('mobile admin shell presents compact navigation',async({page})=>{await page.goto('/admin/reviews');await expect(page).toHaveURL(/admin\/login/)}); });
