import Link from 'next/link';
import {notFound} from 'next/navigation';
import {getStorefrontProduct,getStorefrontProducts,money} from '@/lib/storefront-data';
import {DeliveryPincode} from '@/components/DeliveryPincode';
import {ProductGallery} from '@/components/ProductGallery';
import {ProductPurchase} from '@/components/ProductPurchase';
import {ProductCard} from '@/components/ProductCard';

export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=await getStorefrontProduct(slug);if(!p)return notFound();const related=(await getStorefrontProducts({categorySlug:p.categorySlug})).filter(x=>x.id!==p.id).slice(0,4);const discount=p.mrp>p.price?Math.round((1-p.price/p.mrp)*100):0;return <div className="storefront-page"><div className="page storefront-inner pdp-page"><div className="breadcrumbs"><Link href="/">Home</Link> / <Link href={`/category/${p.categorySlug}`}>{p.category}</Link> / {p.name}</div><div className="pdp-layout"><ProductGallery image={p.image} name={p.name} gallery={p.images.length?p.images:[p.image]}/><section className="pdp-info"><span className="eyebrow dark">{p.category}</span><h1>{p.name}</h1>{p.reviewCount>0&&<div className="pdp-rating"><span>★★★★★</span><b>{p.rating.toFixed(1)}</b><a href="#reviews">{p.reviewCount} reviews</a></div>}<div className="pdp-price"><strong>{money(p.price)}</strong>{p.mrp>p.price&&<><del>{money(p.mrp)}</del><span>{discount}% OFF</span></>}</div><p className="pdp-description">{p.description}</p><div className="pdp-divider"/><ProductPurchase product={p}/><DeliveryPincode weightGrams={500}/><div className="delivery-promises"><div><b>🚚</b><span><strong>Delivery</strong><small>Enter pincode for live availability</small></span></div><div><b>↩</b><span><strong>Easy returns</strong><small>Subject to product eligibility</small></span></div><div><b>♧</b><span><strong>Secure checkout</strong><small>Payment protected end-to-end</small></span></div></div><div className="pdp-accordions"><details open><summary>Product details</summary><p>{p.description}{p.fabric?` Fabric: ${p.fabric}.`:''}{p.care?` Care: ${p.care}.`:''}</p></details><details><summary>Shipping & returns</summary><p>Live delivery availability is checked against your pincode. Returns follow the configured Priyasa policy.</p></details><details id="reviews"><summary>Customer reviews <span>{p.reviewCount?`${p.rating.toFixed(1)} / 5`:'No reviews yet'}</span></summary>{p.reviewCount>0?<p>Based on {p.reviewCount} approved customer reviews.</p>:<p>Be the first to review this product after purchase.</p>}</details></div></section></div></div>{related.length>0&&<section className="section related-products"><div className="section-head"><div><span className="eyebrow dark">YOU MAY ALSO LIKE</span><h2>Complete the edit</h2></div><Link className="text-link" href="/shop">View all →</Link></div><div className="product-grid product-grid-editorial">{related.map(x=><ProductCard key={x.id} product={x}/>)}</div></section>}<div className="mobile-buy-bar"><span>{money(p.price)}</span><Link href="/checkout" className="button dark-button">Buy now</Link></div></div>}
