import {NextResponse} from 'next/server';
import {z} from 'zod';
import {db} from '@/lib/db';
import {requireAdminPermission} from '@/lib/auth';
import {revalidateStorefrontProducts} from '@/lib/storefront-revalidation';

const variant=z.object({sku:z.string().min(2).max(80),size:z.string().min(1).max(30),color:z.string().min(1).max(40),colorHex:z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),price:z.number().int().positive().optional(),stock:z.number().int().min(0).max(100000)});
const schema=z.object({name:z.string().min(2).max(180),slug:z.string().regex(/^[a-z0-9-]+$/).max(180),description:z.string().min(5).max(10000),categoryId:z.string().min(1),brand:z.string().max(120).optional(),mrp:z.number().int().positive(),salePrice:z.number().int().positive(),fabric:z.string().max(120).optional(),care:z.string().max(500).optional(),seoTitle:z.string().max(180).optional(),seoDescription:z.string().max(320).optional(),active:z.boolean().default(true),images:z.array(z.object({url:z.string().url(),alt:z.string().max(180).optional(),sortOrder:z.number().int().min(0).max(100)})).max(20).default([]),variants:z.array(variant).min(1).max(100)}).refine(x=>x.salePrice<=x.mrp,{message:'Sale price cannot exceed MRP',path:['salePrice']});

export async function GET(){try{await requireAdminPermission('products.read');return NextResponse.json({data:await db.product.findMany({include:{category:true,variants:true,images:{orderBy:{sortOrder:'asc'}}},orderBy:{createdAt:'desc'}})});}catch{return NextResponse.json({error:'Forbidden'},{status:403});}}
export async function POST(req:Request){try{const session=await requireAdminPermission('products.write');const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:'Invalid product',details:parsed.error.flatten()},{status:400});const d=parsed.data;const product=await db.$transaction(async tx=>{const p=await tx.product.create({data:{name:d.name,slug:d.slug,description:d.description,categoryId:d.categoryId,brand:d.brand||null,mrp:d.mrp,salePrice:d.salePrice,fabric:d.fabric||null,care:d.care||null,seoTitle:d.seoTitle||null,seoDescription:d.seoDescription||null,active:d.active}});if(d.images.length)await tx.productImage.createMany({data:d.images.map(i=>({...i,productId:p.id}))});await tx.productVariant.createMany({data:d.variants.map(v=>({...v,productId:p.id,price:v.price??d.salePrice,colorHex:v.colorHex||null}))});return p;});await db.auditLog.create({data:{userId:session.userId,action:'CREATE',entity:'Product',entityId:product.id,metadata:{source:'admin'}}});revalidateStorefrontProducts({productSlugs:[product.slug]});return NextResponse.json({data:product},{status:201});}catch(e){return NextResponse.json({error:e instanceof Error&&e.message.includes('FORBIDDEN')?'Forbidden':e instanceof Error&&e.message.includes('Unique constraint')?'Slug or SKU already exists':'Unable to create product'},{status:e instanceof Error&&e.message.includes('FORBIDDEN')?403:409});}}
